#

pluginName = pt.isep.yamldslgen.yamlmde Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_GithubActions_type = Github Actions
_UI_On_type = On
_UI_Push_type = Push
_UI_Pull_request_type = Pull request
_UI_Job_type = Job
_UI_Step_type = Step
_UI_With_type = With
_UI_Permissions_type = Permissions
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_GithubActions_name_feature = Name
_UI_GithubActions_on_feature = On
_UI_GithubActions_jobs_feature = Jobs
_UI_On_push_feature = Push
_UI_On_pullRequest_feature = Pull Request
_UI_Push_branches_feature = Branches
_UI_Push_tags_feature = Tags
_UI_Pull_request_branches_feature = Branches
_UI_Job_id_feature = Id
_UI_Job_runsOn_feature = Runs On
_UI_Job_needs_feature = Needs
_UI_Job_steps_feature = Steps
_UI_Job_permissions_feature = Permissions
_UI_Step_name_feature = Name
_UI_Step_uses_feature = Uses
_UI_Step_run_feature = Run
_UI_Step_with_feature = With
_UI_With_javaVersion_feature = Java Version
_UI_With_distribution_feature = Distribution
_UI_With_name_feature = Name
_UI_With_path_feature = Path
_UI_With_target_feature = Target
_UI_With_token_feature = Token
_UI_With_files_feature = Files
_UI_With_generateReleaseNotes_feature = Generate Release Notes
_UI_Permissions_contents_feature = Contents
_UI_Unknown_feature = Unspecified

<<<<<<< Updated upstream
=======
_UI_KeyValuePair_type = Key Value Pair
_UI_KeyValuePair_key_feature = Key
_UI_KeyValuePair_value_feature = Value
_UI_Schedule_type = Schedule
_UI_Concurrency_type = Concurrency
_UI_Environment_type = Environment
_UI_GithubActions_concurrency_feature = Concurrency
_UI_GithubActions_permissions_feature = Permissions
_UI_GithubActions_env_feature = Env
_UI_Job_name_feature = Name
_UI_Job_environment_feature = Environment
_UI_Step_id_feature = Id
_UI_Step_if_feature = If
_UI_Step_workingDirectory_feature = Working Directory
_UI_Step_env_feature = Env
_UI_On_workflowDispatch_feature = Workflow Dispatch
_UI_On_schedule_feature = Schedule
_UI_Schedule_cron_feature = Cron
_UI_Concurrency_group_feature = Group
_UI_Concurrency_cancelInProgress_feature = Cancel In Progress
_UI_Environment_name_feature = Name
_UI_Environment_url_feature = Url
_UI_Step_shell_feature = Shell
_UI_Permissions_securityEvents_feature = Security Events
_UI_Permissions_actions_feature = Actions
_UI_Permissions_pages_feature = Pages
_UI_Permissions_idToken_feature = Id Token
_UI_Job_if_feature = If
_UI_Pull_request_types_feature = Types
_UI_Permissions_pullRequests_feature = Pull Requests
>>>>>>> Stashed changes
_UI_Step_continueOnError_feature = Continue On Error
_UI_Permissions_issues_feature = Issues
_UI_Strategy_type = Strategy
_UI_Matrix_type = Matrix
_UI_Include_type = Include
_UI_Exclude_type = Exclude
_UI_Workflow_call_type = Workflow call
_UI_Secret_type = Secret
_UI_Job_strategy_feature = Strategy
_UI_On_workflowCall_feature = Workflow Call
_UI_On_pullRequestTarget_feature = Pull Request Target
_UI_Permissions_packages_feature = Packages
_UI_Strategy_failFast_feature = Fail Fast
_UI_Strategy_matrix_feature = Matrix
_UI_Matrix_os_feature = Os
_UI_Matrix_buildType_feature = Build Type
_UI_Matrix_cCompiler_feature = CCompiler
_UI_Matrix_otp_feature = Otp
_UI_Matrix_elixir_feature = Elixir
_UI_Matrix_include_feature = Include
_UI_Matrix_exclude_feature = Exclude
_UI_Include_os_feature = Os
_UI_Include_cCompiler_feature = CCompiler
_UI_Include_cppCompiler_feature = Cpp Compiler
_UI_Exclude_os_feature = Os
_UI_Exclude_cCompiler_feature = CCompiler
_UI_Workflow_call_secrets_feature = Secrets
_UI_Secret_id_feature = Id
_UI_Secret_required_feature = Required
_UI_Container_type = Container
_UI_Job_container_feature = Container
_UI_Container_image_feature = Image
_UI_Defaults_type = Defaults
_UI_Run_type = Run
_UI_Outputs_type = Outputs
_UI_Release_type = Release
_UI_GithubActions_defaults_feature = Defaults
_UI_Job_uses_feature = Uses
_UI_Job_outputs_feature = Outputs
_UI_Job_env_feature = Env
_UI_Job_with_feature = With
_UI_On_release_feature = Release
_UI_Strategy_maxParallel_feature = Max Parallel
_UI_Matrix_pythonVersion_feature = Python Version
_UI_Matrix_configuration_feature = Configuration
_UI_Defaults_run_feature = Run
_UI_Run_shell_feature = Shell
_UI_Outputs_digests_feature = Digests
_UI_Release_types_feature = Types
_UI_On_issues_feature = Issues
_UI_Workflow_dispatch_type = Workflow dispatch
_UI_Input_type = Input
_UI_Workflow_dispatch_inputs_feature = Inputs
_UI_Matrix_nodeVersion_feature = Node Version
_UI_Input_id_feature = Id
_UI_Input_description_feature = Description
_UI_Input_default_feature = Default
_UI_Input_required_feature = Required
_UI_Input_type_feature = Type
_UI_Merge_group_type = Merge group
_UI_On_mergeGroup_feature = Merge Group
_UI_Matrix_rVersion_feature = RVersion
_UI_Merge_group_branches_feature = Branches
_UI_Issues_type = Issues
_UI_Service_type = Service
_UI_Job_services_feature = Services
_UI_On_branchProtectionRule_feature = Branch Protection Rule
_UI_Permissions_models_feature = Models
_UI_Matrix_rubyVersion_feature = Ruby Version
_UI_Issues_types_feature = Types
_UI_Service_id_feature = Id
_UI_Service_image_feature = Image
_UI_Service_ports_feature = Ports
_UI_Service_env_feature = Env
_UI_Job_defaults_feature = Defaults
_UI_Step_timeoutMinutes_feature = Timeout Minutes
_UI_Permissions_checks_feature = Checks
_UI_MatrixParameter_type = Matrix Parameter
_UI_Matrix_parameters_feature = Parameters
_UI_Include_entries_feature = Entries
_UI_Exclude_entries_feature = Entries
_UI_MatrixParameter_key_feature = Key
_UI_MatrixParameter_values_feature = Values
_UI_PermissionsObject_type = Permissions Object
_UI_PermissionsValue_type = Permissions Value
_UI_EnvironmentObject_type = Environment Object
_UI_EnvironmentValue_type = Environment Value
_UI_MatrixObject_type = Matrix Object
_UI_MatrixValue_type = Matrix Value
_UI_PermissionsObject_contents_feature = Contents
_UI_PermissionsObject_securityEvents_feature = Security Events
_UI_PermissionsObject_actions_feature = Actions
_UI_PermissionsObject_pages_feature = Pages
_UI_PermissionsObject_idToken_feature = Id Token
_UI_PermissionsObject_pullRequests_feature = Pull Requests
_UI_PermissionsObject_issues_feature = Issues
_UI_PermissionsObject_packages_feature = Packages
_UI_PermissionsObject_models_feature = Models
_UI_PermissionsObject_checks_feature = Checks
_UI_PermissionsValue_value_feature = Value
_UI_EnvironmentObject_name_feature = Name
_UI_EnvironmentObject_url_feature = Url
_UI_EnvironmentValue_value_feature = Value
_UI_MatrixObject_include_feature = Include
_UI_MatrixObject_exclude_feature = Exclude
_UI_MatrixObject_parameters_feature = Parameters
_UI_MatrixValue_value_feature = Value
_UI_OnObject_type = On Object
_UI_OnValue_type = On Value
_UI_OnObject_branchProtectionRule_feature = Branch Protection Rule
_UI_OnObject_push_feature = Push
_UI_OnObject_pullRequest_feature = Pull Request
_UI_OnObject_schedule_feature = Schedule
_UI_OnObject_workflowDispatch_feature = Workflow Dispatch
_UI_OnObject_workflowCall_feature = Workflow Call
_UI_OnObject_pullRequestTarget_feature = Pull Request Target
_UI_OnObject_release_feature = Release
_UI_OnObject_mergeGroup_feature = Merge Group
_UI_OnObject_issues_feature = Issues
_UI_OnValue_value_feature = Value
