#

pluginName = pt.isep.yamldslgen.yamlmde Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_GithubActions_type = Github Actions
_UI_On_type = On
_UI_Push_type = Push
_UI_Pull_request_type = Pull request
_UI_Job_type = Job
_UI_Step_type = Step
_UI_With_type = With
_UI_Permissions_type = Permissions
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_GithubActions_name_feature = Name
_UI_GithubActions_on_feature = On
_UI_GithubActions_jobs_feature = Jobs
_UI_On_push_feature = Push
_UI_On_pullRequest_feature = Pull Request
_UI_Push_branches_feature = Branches
_UI_Push_tags_feature = Tags
_UI_Pull_request_branches_feature = Branches
_UI_Job_id_feature = Id
_UI_Job_runsOn_feature = Runs On
_UI_Job_needs_feature = Needs
_UI_Job_steps_feature = Steps
_UI_Job_permissions_feature = Permissions
_UI_Step_name_feature = Name
_UI_Step_uses_feature = Uses
_UI_Step_run_feature = Run
_UI_Step_with_feature = With
_UI_With_javaVersion_feature = Java Version
_UI_With_distribution_feature = Distribution
_UI_With_name_feature = Name
_UI_With_path_feature = Path
_UI_With_target_feature = Target
_UI_With_token_feature = Token
_UI_With_files_feature = Files
_UI_With_generateReleaseNotes_feature = Generate Release Notes
_UI_Permissions_contents_feature = Contents
_UI_Unknown_feature = Unspecified

