/**
 */
package pt.isep.yamldslgen.docker_compose.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import pt.isep.yamldslgen.docker_compose.util.DockercomposeAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class DockercomposeItemProviderAdapterFactory extends DockercomposeAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DockercomposeItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.KeyValuePair} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected KeyValuePairItemProvider keyValuePairItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.KeyValuePair}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createKeyValuePairAdapter() {
		if (keyValuePairItemProvider == null) {
			keyValuePairItemProvider = new KeyValuePairItemProvider(this);
		}

		return keyValuePairItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.DockerCompose} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DockerComposeItemProvider dockerComposeItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.DockerCompose}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDockerComposeAdapter() {
		if (dockerComposeItemProvider == null) {
			dockerComposeItemProvider = new DockerComposeItemProvider(this);
		}

		return dockerComposeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.Service} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceItemProvider serviceItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.Service}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceAdapter() {
		if (serviceItemProvider == null) {
			serviceItemProvider = new ServiceItemProvider(this);
		}

		return serviceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.Healthcheck} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected HealthcheckItemProvider healthcheckItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.Healthcheck}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createHealthcheckAdapter() {
		if (healthcheckItemProvider == null) {
			healthcheckItemProvider = new HealthcheckItemProvider(this);
		}

		return healthcheckItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.Network} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NetworkItemProvider networkItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.Network}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNetworkAdapter() {
		if (networkItemProvider == null) {
			networkItemProvider = new NetworkItemProvider(this);
		}

		return networkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.Resource} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ResourceItemProvider resourceItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.Resource}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createResourceAdapter() {
		if (resourceItemProvider == null) {
			resourceItemProvider = new ResourceItemProvider(this);
		}

		return resourceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.Secret} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SecretItemProvider secretItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.Secret}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSecretAdapter() {
		if (secretItemProvider == null) {
			secretItemProvider = new SecretItemProvider(this);
		}

		return secretItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.Db} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DbItemProvider dbItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.Db}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDbAdapter() {
		if (dbItemProvider == null) {
			dbItemProvider = new DbItemProvider(this);
		}

		return dbItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.Config} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConfigItemProvider configItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.Config}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConfigAdapter() {
		if (configItemProvider == null) {
			configItemProvider = new ConfigItemProvider(this);
		}

		return configItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.VolumeObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VolumeObjectItemProvider volumeObjectItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.VolumeObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVolumeObjectAdapter() {
		if (volumeObjectItemProvider == null) {
			volumeObjectItemProvider = new VolumeObjectItemProvider(this);
		}

		return volumeObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.VolumeValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VolumeValueItemProvider volumeValueItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.VolumeValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVolumeValueAdapter() {
		if (volumeValueItemProvider == null) {
			volumeValueItemProvider = new VolumeValueItemProvider(this);
		}

		return volumeValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.BuildObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BuildObjectItemProvider buildObjectItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.BuildObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBuildObjectAdapter() {
		if (buildObjectItemProvider == null) {
			buildObjectItemProvider = new BuildObjectItemProvider(this);
		}

		return buildObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.BuildValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BuildValueItemProvider buildValueItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.BuildValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBuildValueAdapter() {
		if (buildValueItemProvider == null) {
			buildValueItemProvider = new BuildValueItemProvider(this);
		}

		return buildValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.NetworksObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NetworksObjectItemProvider networksObjectItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.NetworksObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNetworksObjectAdapter() {
		if (networksObjectItemProvider == null) {
			networksObjectItemProvider = new NetworksObjectItemProvider(this);
		}

		return networksObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.NetworksValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NetworksValueItemProvider networksValueItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.NetworksValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNetworksValueAdapter() {
		if (networksValueItemProvider == null) {
			networksValueItemProvider = new NetworksValueItemProvider(this);
		}

		return networksValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.Depends_onObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Depends_onObjectItemProvider depends_onObjectItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.Depends_onObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDepends_onObjectAdapter() {
		if (depends_onObjectItemProvider == null) {
			depends_onObjectItemProvider = new Depends_onObjectItemProvider(this);
		}

		return depends_onObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.docker_compose.Depends_onValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Depends_onValueItemProvider depends_onValueItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.docker_compose.Depends_onValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDepends_onValueAdapter() {
		if (depends_onValueItemProvider == null) {
			depends_onValueItemProvider = new Depends_onValueItemProvider(this);
		}

		return depends_onValueItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (keyValuePairItemProvider != null)
			keyValuePairItemProvider.dispose();
		if (dockerComposeItemProvider != null)
			dockerComposeItemProvider.dispose();
		if (serviceItemProvider != null)
			serviceItemProvider.dispose();
		if (healthcheckItemProvider != null)
			healthcheckItemProvider.dispose();
		if (networkItemProvider != null)
			networkItemProvider.dispose();
		if (resourceItemProvider != null)
			resourceItemProvider.dispose();
		if (secretItemProvider != null)
			secretItemProvider.dispose();
		if (dbItemProvider != null)
			dbItemProvider.dispose();
		if (configItemProvider != null)
			configItemProvider.dispose();
		if (volumeObjectItemProvider != null)
			volumeObjectItemProvider.dispose();
		if (volumeValueItemProvider != null)
			volumeValueItemProvider.dispose();
		if (buildObjectItemProvider != null)
			buildObjectItemProvider.dispose();
		if (buildValueItemProvider != null)
			buildValueItemProvider.dispose();
		if (networksObjectItemProvider != null)
			networksObjectItemProvider.dispose();
		if (networksValueItemProvider != null)
			networksValueItemProvider.dispose();
		if (depends_onObjectItemProvider != null)
			depends_onObjectItemProvider.dispose();
		if (depends_onValueItemProvider != null)
			depends_onValueItemProvider.dispose();
	}

}
