/*
 * generated by Xtext 2.42.0
 */
package pt.isep.yamldslgen.dockercompose.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import pt.isep.yamldslgen.dockercompose.xtext.ui.internal.XtextActivator;

public class DcDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("pt.isep.yamldslgen.dockercompose.xtext.DcDsl");
	}

}
