/*
 * generated by Xtext 2.42.0
 */
package pt.isep.yamldslgen.dockercompose.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class DcDslUiModule extends AbstractDcDslUiModule {

	public DcDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
