/*
 * generated by Xtext 2.42.0
 */
package pt.isep.yamldslgen.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import pt.isep.yamldslgen.xtext.ide.contentassist.antlr.internal.InternalMyDslParser;
import pt.isep.yamldslgen.xtext.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getPlainScalarAccess().getAlternatives_0(), "rule__PlainScalar__Alternatives_0");
			builder.put(grammarAccess.getPlainScalarAccess().getAlternatives_1(), "rule__PlainScalar__Alternatives_1");
			builder.put(grammarAccess.getJobAccess().getAlternatives_3_1_2(), "rule__Job__Alternatives_3_1_2");
			builder.put(grammarAccess.getPushAccess().getAlternatives_2_0_2(), "rule__Push__Alternatives_2_0_2");
			builder.put(grammarAccess.getPushAccess().getAlternatives_2_1_2(), "rule__Push__Alternatives_2_1_2");
<<<<<<< Updated upstream
			builder.put(grammarAccess.getPull_requestAccess().getAlternatives_4(), "rule__Pull_request__Alternatives_4");
=======
			builder.put(grammarAccess.getPull_requestAccess().getAlternatives_2_0_2(), "rule__Pull_request__Alternatives_2_0_2");
			builder.put(grammarAccess.getPull_requestAccess().getAlternatives_2_1_2(), "rule__Pull_request__Alternatives_2_1_2");
			builder.put(grammarAccess.getJobAccess().getAlternatives_3_2_2(), "rule__Job__Alternatives_3_2_2");
>>>>>>> Stashed changes
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getGithubActionsAccess().getGroup_0(), "rule__GithubActions__Group_0__0");
			builder.put(grammarAccess.getGithubActionsAccess().getGroup_1(), "rule__GithubActions__Group_1__0");
			builder.put(grammarAccess.getGithubActionsAccess().getGroup_2(), "rule__GithubActions__Group_2__0");
			builder.put(grammarAccess.getPlainScalarAccess().getGroup(), "rule__PlainScalar__Group__0");
			builder.put(grammarAccess.getOnAccess().getGroup(), "rule__On__Group__0");
			builder.put(grammarAccess.getOnAccess().getGroup_2_0(), "rule__On__Group_2_0__0");
			builder.put(grammarAccess.getOnAccess().getGroup_2_1(), "rule__On__Group_2_1__0");
			builder.put(grammarAccess.getJobAccess().getGroup(), "rule__Job__Group__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_0(), "rule__Job__Group_3_0__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_1(), "rule__Job__Group_3_1__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_1_2_0(), "rule__Job__Group_3_1_2_0__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_1_2_0_1(), "rule__Job__Group_3_1_2_0_1__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_1_2_1(), "rule__Job__Group_3_1_2_1__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_1_2_1_2(), "rule__Job__Group_3_1_2_1_2__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_2(), "rule__Job__Group_3_2__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_3(), "rule__Job__Group_3_3__0");
			builder.put(grammarAccess.getPushAccess().getGroup(), "rule__Push__Group__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_0(), "rule__Push__Group_2_0__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_0_2_0(), "rule__Push__Group_2_0_2_0__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_0_2_0_1(), "rule__Push__Group_2_0_2_0_1__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_0_2_1(), "rule__Push__Group_2_0_2_1__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_0_2_1_2(), "rule__Push__Group_2_0_2_1_2__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_1(), "rule__Push__Group_2_1__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_1_2_0(), "rule__Push__Group_2_1_2_0__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_1_2_0_1(), "rule__Push__Group_2_1_2_0_1__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_1_2_1(), "rule__Push__Group_2_1_2_1__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_1_2_1_2(), "rule__Push__Group_2_1_2_1_2__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup(), "rule__Pull_request__Group__0");
<<<<<<< Updated upstream
			builder.put(grammarAccess.getPull_requestAccess().getGroup_4_0(), "rule__Pull_request__Group_4_0__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_4_0_1(), "rule__Pull_request__Group_4_0_1__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_4_1(), "rule__Pull_request__Group_4_1__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_4_1_2(), "rule__Pull_request__Group_4_1_2__0");
=======
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_0(), "rule__Pull_request__Group_2_0__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_0_2_0(), "rule__Pull_request__Group_2_0_2_0__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_0_2_0_1(), "rule__Pull_request__Group_2_0_2_0_1__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_0_2_1(), "rule__Pull_request__Group_2_0_2_1__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_0_2_1_2(), "rule__Pull_request__Group_2_0_2_1_2__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_1(), "rule__Pull_request__Group_2_1__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_1_2_0(), "rule__Pull_request__Group_2_1_2_0__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_1_2_0_1(), "rule__Pull_request__Group_2_1_2_0_1__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_1_2_1(), "rule__Pull_request__Group_2_1_2_1__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_1_2_1_2(), "rule__Pull_request__Group_2_1_2_1_2__0");
			builder.put(grammarAccess.getScheduleAccess().getGroup(), "rule__Schedule__Group__0");
			builder.put(grammarAccess.getConcurrencyAccess().getGroup(), "rule__Concurrency__Group__0");
			builder.put(grammarAccess.getConcurrencyAccess().getGroup_2_0(), "rule__Concurrency__Group_2_0__0");
			builder.put(grammarAccess.getConcurrencyAccess().getGroup_2_1(), "rule__Concurrency__Group_2_1__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup(), "rule__Environment__Group__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup_2_0(), "rule__Environment__Group_2_0__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup_2_1(), "rule__Environment__Group_2_1__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup(), "rule__Permissions__Group__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_0(), "rule__Permissions__Group_2_0__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_1(), "rule__Permissions__Group_2_1__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_2(), "rule__Permissions__Group_2_2__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_3(), "rule__Permissions__Group_2_3__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_4(), "rule__Permissions__Group_2_4__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_5(), "rule__Permissions__Group_2_5__0");
			builder.put(grammarAccess.getJobAccess().getGroup(), "rule__Job__Group__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_0(), "rule__Job__Group_3_0__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_1(), "rule__Job__Group_3_1__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_2(), "rule__Job__Group_3_2__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_2_2_1(), "rule__Job__Group_3_2_2_1__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_2_2_1_1(), "rule__Job__Group_3_2_2_1_1__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_2_2_2(), "rule__Job__Group_3_2_2_2__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_2_2_2_2(), "rule__Job__Group_3_2_2_2_2__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_3(), "rule__Job__Group_3_3__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_4(), "rule__Job__Group_3_4__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_5(), "rule__Job__Group_3_5__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_6(), "rule__Job__Group_3_6__0");
>>>>>>> Stashed changes
			builder.put(grammarAccess.getStepAccess().getGroup(), "rule__Step__Group__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_0(), "rule__Step__Group_3_0__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_1(), "rule__Step__Group_3_1__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_2(), "rule__Step__Group_3_2__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_3(), "rule__Step__Group_3_3__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup(), "rule__Permissions__Group__0");
			builder.put(grammarAccess.getWithAccess().getGroup(), "rule__With__Group__0");
			builder.put(grammarAccess.getWithAccess().getGroup_2_0(), "rule__With__Group_2_0__0");
			builder.put(grammarAccess.getWithAccess().getGroup_2_1(), "rule__With__Group_2_1__0");
			builder.put(grammarAccess.getWithAccess().getGroup_2_2(), "rule__With__Group_2_2__0");
			builder.put(grammarAccess.getWithAccess().getGroup_2_3(), "rule__With__Group_2_3__0");
			builder.put(grammarAccess.getWithAccess().getGroup_2_4(), "rule__With__Group_2_4__0");
			builder.put(grammarAccess.getWithAccess().getGroup_2_5(), "rule__With__Group_2_5__0");
			builder.put(grammarAccess.getWithAccess().getGroup_2_6(), "rule__With__Group_2_6__0");
			builder.put(grammarAccess.getWithAccess().getGroup_2_7(), "rule__With__Group_2_7__0");
			builder.put(grammarAccess.getGithubActionsAccess().getNameAssignment_0_2(), "rule__GithubActions__NameAssignment_0_2");
			builder.put(grammarAccess.getGithubActionsAccess().getOnAssignment_1_2(), "rule__GithubActions__OnAssignment_1_2");
			builder.put(grammarAccess.getGithubActionsAccess().getJobsAssignment_2_3(), "rule__GithubActions__JobsAssignment_2_3");
			builder.put(grammarAccess.getOnAccess().getPushAssignment_2_0_2(), "rule__On__PushAssignment_2_0_2");
			builder.put(grammarAccess.getOnAccess().getPullRequestAssignment_2_1_2(), "rule__On__PullRequestAssignment_2_1_2");
			builder.put(grammarAccess.getJobAccess().getIdAssignment_0(), "rule__Job__IdAssignment_0");
			builder.put(grammarAccess.getJobAccess().getRunsOnAssignment_3_0_2(), "rule__Job__RunsOnAssignment_3_0_2");
			builder.put(grammarAccess.getJobAccess().getNeedsAssignment_3_1_2_0_1_2(), "rule__Job__NeedsAssignment_3_1_2_0_1_2");
			builder.put(grammarAccess.getJobAccess().getNeedsAssignment_3_1_2_1_1(), "rule__Job__NeedsAssignment_3_1_2_1_1");
			builder.put(grammarAccess.getJobAccess().getNeedsAssignment_3_1_2_1_2_1(), "rule__Job__NeedsAssignment_3_1_2_1_2_1");
			builder.put(grammarAccess.getJobAccess().getStepsAssignment_3_2_3(), "rule__Job__StepsAssignment_3_2_3");
			builder.put(grammarAccess.getJobAccess().getPermissionsAssignment_3_3_2(), "rule__Job__PermissionsAssignment_3_3_2");
			builder.put(grammarAccess.getPushAccess().getBranchesAssignment_2_0_2_0_1_2(), "rule__Push__BranchesAssignment_2_0_2_0_1_2");
			builder.put(grammarAccess.getPushAccess().getBranchesAssignment_2_0_2_1_1(), "rule__Push__BranchesAssignment_2_0_2_1_1");
			builder.put(grammarAccess.getPushAccess().getBranchesAssignment_2_0_2_1_2_1(), "rule__Push__BranchesAssignment_2_0_2_1_2_1");
			builder.put(grammarAccess.getPushAccess().getTagsAssignment_2_1_2_0_1_2(), "rule__Push__TagsAssignment_2_1_2_0_1_2");
			builder.put(grammarAccess.getPushAccess().getTagsAssignment_2_1_2_1_1(), "rule__Push__TagsAssignment_2_1_2_1_1");
			builder.put(grammarAccess.getPushAccess().getTagsAssignment_2_1_2_1_2_1(), "rule__Push__TagsAssignment_2_1_2_1_2_1");
<<<<<<< Updated upstream
			builder.put(grammarAccess.getPull_requestAccess().getBranchesAssignment_4_0_1_2(), "rule__Pull_request__BranchesAssignment_4_0_1_2");
			builder.put(grammarAccess.getPull_requestAccess().getBranchesAssignment_4_1_1(), "rule__Pull_request__BranchesAssignment_4_1_1");
			builder.put(grammarAccess.getPull_requestAccess().getBranchesAssignment_4_1_2_1(), "rule__Pull_request__BranchesAssignment_4_1_2_1");
=======
			builder.put(grammarAccess.getPull_requestAccess().getBranchesAssignment_2_0_2_0_1_2(), "rule__Pull_request__BranchesAssignment_2_0_2_0_1_2");
			builder.put(grammarAccess.getPull_requestAccess().getBranchesAssignment_2_0_2_1_1(), "rule__Pull_request__BranchesAssignment_2_0_2_1_1");
			builder.put(grammarAccess.getPull_requestAccess().getBranchesAssignment_2_0_2_1_2_1(), "rule__Pull_request__BranchesAssignment_2_0_2_1_2_1");
			builder.put(grammarAccess.getPull_requestAccess().getTypesAssignment_2_1_2_0_1_2(), "rule__Pull_request__TypesAssignment_2_1_2_0_1_2");
			builder.put(grammarAccess.getPull_requestAccess().getTypesAssignment_2_1_2_1_1(), "rule__Pull_request__TypesAssignment_2_1_2_1_1");
			builder.put(grammarAccess.getPull_requestAccess().getTypesAssignment_2_1_2_1_2_1(), "rule__Pull_request__TypesAssignment_2_1_2_1_2_1");
			builder.put(grammarAccess.getScheduleAccess().getCronAssignment_4(), "rule__Schedule__CronAssignment_4");
			builder.put(grammarAccess.getConcurrencyAccess().getGroupAssignment_2_0_2(), "rule__Concurrency__GroupAssignment_2_0_2");
			builder.put(grammarAccess.getConcurrencyAccess().getCancelInProgressAssignment_2_1_2(), "rule__Concurrency__CancelInProgressAssignment_2_1_2");
			builder.put(grammarAccess.getEnvironmentAccess().getNameAssignment_2_0_2(), "rule__Environment__NameAssignment_2_0_2");
			builder.put(grammarAccess.getEnvironmentAccess().getUrlAssignment_2_1_2(), "rule__Environment__UrlAssignment_2_1_2");
			builder.put(grammarAccess.getPermissionsAccess().getContentsAssignment_2_0_2(), "rule__Permissions__ContentsAssignment_2_0_2");
			builder.put(grammarAccess.getPermissionsAccess().getSecurityEventsAssignment_2_1_2(), "rule__Permissions__SecurityEventsAssignment_2_1_2");
			builder.put(grammarAccess.getPermissionsAccess().getActionsAssignment_2_2_2(), "rule__Permissions__ActionsAssignment_2_2_2");
			builder.put(grammarAccess.getPermissionsAccess().getPagesAssignment_2_3_2(), "rule__Permissions__PagesAssignment_2_3_2");
			builder.put(grammarAccess.getPermissionsAccess().getIdTokenAssignment_2_4_2(), "rule__Permissions__IdTokenAssignment_2_4_2");
			builder.put(grammarAccess.getPermissionsAccess().getPullRequestsAssignment_2_5_2(), "rule__Permissions__PullRequestsAssignment_2_5_2");
			builder.put(grammarAccess.getJobAccess().getIdAssignment_0(), "rule__Job__IdAssignment_0");
			builder.put(grammarAccess.getJobAccess().getNameAssignment_3_0_2(), "rule__Job__NameAssignment_3_0_2");
			builder.put(grammarAccess.getJobAccess().getRunsOnAssignment_3_1_2(), "rule__Job__RunsOnAssignment_3_1_2");
			builder.put(grammarAccess.getJobAccess().getNeedsAssignment_3_2_2_0(), "rule__Job__NeedsAssignment_3_2_2_0");
			builder.put(grammarAccess.getJobAccess().getNeedsAssignment_3_2_2_1_1_2(), "rule__Job__NeedsAssignment_3_2_2_1_1_2");
			builder.put(grammarAccess.getJobAccess().getNeedsAssignment_3_2_2_2_1(), "rule__Job__NeedsAssignment_3_2_2_2_1");
			builder.put(grammarAccess.getJobAccess().getNeedsAssignment_3_2_2_2_2_1(), "rule__Job__NeedsAssignment_3_2_2_2_2_1");
			builder.put(grammarAccess.getJobAccess().getIfAssignment_3_3_2(), "rule__Job__IfAssignment_3_3_2");
			builder.put(grammarAccess.getJobAccess().getEnvironmentAssignment_3_4_2(), "rule__Job__EnvironmentAssignment_3_4_2");
			builder.put(grammarAccess.getJobAccess().getStepsAssignment_3_5_3(), "rule__Job__StepsAssignment_3_5_3");
			builder.put(grammarAccess.getJobAccess().getPermissionsAssignment_3_6_2(), "rule__Job__PermissionsAssignment_3_6_2");
>>>>>>> Stashed changes
			builder.put(grammarAccess.getStepAccess().getNameAssignment_3_0_2(), "rule__Step__NameAssignment_3_0_2");
			builder.put(grammarAccess.getStepAccess().getUsesAssignment_3_1_2(), "rule__Step__UsesAssignment_3_1_2");
			builder.put(grammarAccess.getStepAccess().getRunAssignment_3_2_2(), "rule__Step__RunAssignment_3_2_2");
			builder.put(grammarAccess.getStepAccess().getWithAssignment_3_3_2(), "rule__Step__WithAssignment_3_3_2");
			builder.put(grammarAccess.getPermissionsAccess().getContentsAssignment_4(), "rule__Permissions__ContentsAssignment_4");
			builder.put(grammarAccess.getWithAccess().getNameAssignment_2_0_2(), "rule__With__NameAssignment_2_0_2");
			builder.put(grammarAccess.getWithAccess().getJavaVersionAssignment_2_1_2(), "rule__With__JavaVersionAssignment_2_1_2");
			builder.put(grammarAccess.getWithAccess().getDistributionAssignment_2_2_2(), "rule__With__DistributionAssignment_2_2_2");
			builder.put(grammarAccess.getWithAccess().getPathAssignment_2_3_2(), "rule__With__PathAssignment_2_3_2");
			builder.put(grammarAccess.getWithAccess().getTargetAssignment_2_4_2(), "rule__With__TargetAssignment_2_4_2");
			builder.put(grammarAccess.getWithAccess().getTokenAssignment_2_5_2(), "rule__With__TokenAssignment_2_5_2");
			builder.put(grammarAccess.getWithAccess().getFilesAssignment_2_6_2(), "rule__With__FilesAssignment_2_6_2");
			builder.put(grammarAccess.getWithAccess().getGenerateReleaseNotesAssignment_2_7_2(), "rule__With__GenerateReleaseNotesAssignment_2_7_2");
			builder.put(grammarAccess.getGithubActionsAccess().getUnorderedGroup(), "rule__GithubActions__UnorderedGroup");
			builder.put(grammarAccess.getOnAccess().getUnorderedGroup_2(), "rule__On__UnorderedGroup_2");
<<<<<<< Updated upstream
=======
			builder.put(grammarAccess.getPushAccess().getUnorderedGroup_2(), "rule__Push__UnorderedGroup_2");
			builder.put(grammarAccess.getPull_requestAccess().getUnorderedGroup_2(), "rule__Pull_request__UnorderedGroup_2");
			builder.put(grammarAccess.getConcurrencyAccess().getUnorderedGroup_2(), "rule__Concurrency__UnorderedGroup_2");
			builder.put(grammarAccess.getEnvironmentAccess().getUnorderedGroup_2(), "rule__Environment__UnorderedGroup_2");
			builder.put(grammarAccess.getPermissionsAccess().getUnorderedGroup_2(), "rule__Permissions__UnorderedGroup_2");
>>>>>>> Stashed changes
			builder.put(grammarAccess.getJobAccess().getUnorderedGroup_3(), "rule__Job__UnorderedGroup_3");
			builder.put(grammarAccess.getPushAccess().getUnorderedGroup_2(), "rule__Push__UnorderedGroup_2");
			builder.put(grammarAccess.getStepAccess().getUnorderedGroup_3(), "rule__Step__UnorderedGroup_3");
			builder.put(grammarAccess.getWithAccess().getUnorderedGroup_2(), "rule__With__UnorderedGroup_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
