/*
 * generated by Xtext 2.42.0
 */
package pt.isep.yamldslgen.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import pt.isep.yamldslgen.xtext.ide.contentassist.antlr.internal.InternalMyDslParser;
import pt.isep.yamldslgen.xtext.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MyDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MyDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getScalarSequenceAccess().getAlternatives_0(), "rule__ScalarSequence__Alternatives_0");
			builder.put(grammarAccess.getScalarSequenceAccess().getAlternatives_1_1(), "rule__ScalarSequence__Alternatives_1_1");
			builder.put(grammarAccess.getBlockStringAccess().getAlternatives_0(), "rule__BlockString__Alternatives_0");
			builder.put(grammarAccess.getBlockStringAccess().getAlternatives_2(), "rule__BlockString__Alternatives_2");
			builder.put(grammarAccess.getKeyNameAccess().getAlternatives(), "rule__KeyName__Alternatives");
			builder.put(grammarAccess.getPushAccess().getAlternatives_2_0_2(), "rule__Push__Alternatives_2_0_2");
			builder.put(grammarAccess.getPushAccess().getAlternatives_2_1_2(), "rule__Push__Alternatives_2_1_2");
			builder.put(grammarAccess.getPull_requestAccess().getAlternatives_2_0_2(), "rule__Pull_request__Alternatives_2_0_2");
			builder.put(grammarAccess.getPull_requestAccess().getAlternatives_2_1_2(), "rule__Pull_request__Alternatives_2_1_2");
			builder.put(grammarAccess.getJobAccess().getAlternatives_3_2_2(), "rule__Job__Alternatives_3_2_2");
			builder.put(grammarAccess.getMatrixAccess().getAlternatives_2_0_2(), "rule__Matrix__Alternatives_2_0_2");
			builder.put(grammarAccess.getMatrixAccess().getAlternatives_2_1_2(), "rule__Matrix__Alternatives_2_1_2");
			builder.put(grammarAccess.getMatrixAccess().getAlternatives_2_2_2(), "rule__Matrix__Alternatives_2_2_2");
			builder.put(grammarAccess.getMatrixAccess().getAlternatives_2_3_2(), "rule__Matrix__Alternatives_2_3_2");
			builder.put(grammarAccess.getMatrixAccess().getAlternatives_2_4_2(), "rule__Matrix__Alternatives_2_4_2");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getGithubActionsAccess().getGroup_0(), "rule__GithubActions__Group_0__0");
			builder.put(grammarAccess.getGithubActionsAccess().getGroup_1(), "rule__GithubActions__Group_1__0");
			builder.put(grammarAccess.getGithubActionsAccess().getGroup_2(), "rule__GithubActions__Group_2__0");
			builder.put(grammarAccess.getGithubActionsAccess().getGroup_3(), "rule__GithubActions__Group_3__0");
			builder.put(grammarAccess.getGithubActionsAccess().getGroup_4(), "rule__GithubActions__Group_4__0");
			builder.put(grammarAccess.getGithubActionsAccess().getGroup_5(), "rule__GithubActions__Group_5__0");
			builder.put(grammarAccess.getGithubActionsAccess().getGroup_5_2(), "rule__GithubActions__Group_5_2__0");
			builder.put(grammarAccess.getScalarSequenceAccess().getGroup(), "rule__ScalarSequence__Group__0");
			builder.put(grammarAccess.getScalarSequenceAccess().getGroup_1(), "rule__ScalarSequence__Group_1__0");
			builder.put(grammarAccess.getBlockStringAccess().getGroup(), "rule__BlockString__Group__0");
			builder.put(grammarAccess.getKeyValuePairAccess().getGroup(), "rule__KeyValuePair__Group__0");
			builder.put(grammarAccess.getOnAccess().getGroup(), "rule__On__Group__0");
			builder.put(grammarAccess.getOnAccess().getGroup_2_0(), "rule__On__Group_2_0__0");
			builder.put(grammarAccess.getOnAccess().getGroup_2_1(), "rule__On__Group_2_1__0");
			builder.put(grammarAccess.getOnAccess().getGroup_2_2(), "rule__On__Group_2_2__0");
			builder.put(grammarAccess.getOnAccess().getGroup_2_3(), "rule__On__Group_2_3__0");
			builder.put(grammarAccess.getOnAccess().getGroup_2_3_2(), "rule__On__Group_2_3_2__0");
			builder.put(grammarAccess.getOnAccess().getGroup_2_4(), "rule__On__Group_2_4__0");
			builder.put(grammarAccess.getOnAccess().getGroup_2_5(), "rule__On__Group_2_5__0");
			builder.put(grammarAccess.getPushAccess().getGroup(), "rule__Push__Group__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_0(), "rule__Push__Group_2_0__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_0_2_0(), "rule__Push__Group_2_0_2_0__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_0_2_0_1(), "rule__Push__Group_2_0_2_0_1__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_0_2_1(), "rule__Push__Group_2_0_2_1__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_0_2_1_2(), "rule__Push__Group_2_0_2_1_2__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_1(), "rule__Push__Group_2_1__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_1_2_0(), "rule__Push__Group_2_1_2_0__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_1_2_0_1(), "rule__Push__Group_2_1_2_0_1__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_1_2_1(), "rule__Push__Group_2_1_2_1__0");
			builder.put(grammarAccess.getPushAccess().getGroup_2_1_2_1_2(), "rule__Push__Group_2_1_2_1_2__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup(), "rule__Pull_request__Group__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_0(), "rule__Pull_request__Group_2_0__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_0_2_0(), "rule__Pull_request__Group_2_0_2_0__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_0_2_0_1(), "rule__Pull_request__Group_2_0_2_0_1__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_0_2_1(), "rule__Pull_request__Group_2_0_2_1__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_0_2_1_2(), "rule__Pull_request__Group_2_0_2_1_2__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_1(), "rule__Pull_request__Group_2_1__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_1_2_0(), "rule__Pull_request__Group_2_1_2_0__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_1_2_0_1(), "rule__Pull_request__Group_2_1_2_0_1__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_1_2_1(), "rule__Pull_request__Group_2_1_2_1__0");
			builder.put(grammarAccess.getPull_requestAccess().getGroup_2_1_2_1_2(), "rule__Pull_request__Group_2_1_2_1_2__0");
			builder.put(grammarAccess.getScheduleAccess().getGroup(), "rule__Schedule__Group__0");
			builder.put(grammarAccess.getWorkflow_callAccess().getGroup(), "rule__Workflow_call__Group__0");
			builder.put(grammarAccess.getWorkflow_callAccess().getGroup_2(), "rule__Workflow_call__Group_2__0");
			builder.put(grammarAccess.getSecretAccess().getGroup(), "rule__Secret__Group__0");
			builder.put(grammarAccess.getSecretAccess().getGroup_3(), "rule__Secret__Group_3__0");
			builder.put(grammarAccess.getConcurrencyAccess().getGroup(), "rule__Concurrency__Group__0");
			builder.put(grammarAccess.getConcurrencyAccess().getGroup_2_0(), "rule__Concurrency__Group_2_0__0");
			builder.put(grammarAccess.getConcurrencyAccess().getGroup_2_1(), "rule__Concurrency__Group_2_1__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup(), "rule__Environment__Group__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup_2_0(), "rule__Environment__Group_2_0__0");
			builder.put(grammarAccess.getEnvironmentAccess().getGroup_2_1(), "rule__Environment__Group_2_1__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup(), "rule__Permissions__Group__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_0(), "rule__Permissions__Group_2_0__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_1(), "rule__Permissions__Group_2_1__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_2(), "rule__Permissions__Group_2_2__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_3(), "rule__Permissions__Group_2_3__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_4(), "rule__Permissions__Group_2_4__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_5(), "rule__Permissions__Group_2_5__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_6(), "rule__Permissions__Group_2_6__0");
			builder.put(grammarAccess.getPermissionsAccess().getGroup_2_7(), "rule__Permissions__Group_2_7__0");
			builder.put(grammarAccess.getJobAccess().getGroup(), "rule__Job__Group__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_0(), "rule__Job__Group_3_0__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_1(), "rule__Job__Group_3_1__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_2(), "rule__Job__Group_3_2__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_2_2_1(), "rule__Job__Group_3_2_2_1__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_2_2_1_1(), "rule__Job__Group_3_2_2_1_1__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_2_2_2(), "rule__Job__Group_3_2_2_2__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_2_2_2_2(), "rule__Job__Group_3_2_2_2_2__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_3(), "rule__Job__Group_3_3__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_4(), "rule__Job__Group_3_4__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_5(), "rule__Job__Group_3_5__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_6(), "rule__Job__Group_3_6__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_7(), "rule__Job__Group_3_7__0");
			builder.put(grammarAccess.getJobAccess().getGroup_3_8(), "rule__Job__Group_3_8__0");
			builder.put(grammarAccess.getStepAccess().getGroup(), "rule__Step__Group__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_0(), "rule__Step__Group_3_0__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_1(), "rule__Step__Group_3_1__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_2(), "rule__Step__Group_3_2__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_3(), "rule__Step__Group_3_3__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_4(), "rule__Step__Group_3_4__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_5(), "rule__Step__Group_3_5__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_6(), "rule__Step__Group_3_6__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_7(), "rule__Step__Group_3_7__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_8(), "rule__Step__Group_3_8__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_8_2(), "rule__Step__Group_3_8_2__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_9(), "rule__Step__Group_3_9__0");
			builder.put(grammarAccess.getStepAccess().getGroup_3_9_2(), "rule__Step__Group_3_9_2__0");
			builder.put(grammarAccess.getStrategyAccess().getGroup(), "rule__Strategy__Group__0");
			builder.put(grammarAccess.getStrategyAccess().getGroup_2_0(), "rule__Strategy__Group_2_0__0");
			builder.put(grammarAccess.getStrategyAccess().getGroup_2_1(), "rule__Strategy__Group_2_1__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup(), "rule__Matrix__Group__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_0(), "rule__Matrix__Group_2_0__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_0_2_0(), "rule__Matrix__Group_2_0_2_0__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_0_2_0_1(), "rule__Matrix__Group_2_0_2_0_1__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_0_2_1(), "rule__Matrix__Group_2_0_2_1__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_0_2_1_2(), "rule__Matrix__Group_2_0_2_1_2__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_1(), "rule__Matrix__Group_2_1__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_1_2_0(), "rule__Matrix__Group_2_1_2_0__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_1_2_0_1(), "rule__Matrix__Group_2_1_2_0_1__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_1_2_1(), "rule__Matrix__Group_2_1_2_1__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_1_2_1_2(), "rule__Matrix__Group_2_1_2_1_2__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_2(), "rule__Matrix__Group_2_2__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_2_2_0(), "rule__Matrix__Group_2_2_2_0__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_2_2_0_1(), "rule__Matrix__Group_2_2_2_0_1__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_2_2_1(), "rule__Matrix__Group_2_2_2_1__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_2_2_1_2(), "rule__Matrix__Group_2_2_2_1_2__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_3(), "rule__Matrix__Group_2_3__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_3_2_0(), "rule__Matrix__Group_2_3_2_0__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_3_2_0_1(), "rule__Matrix__Group_2_3_2_0_1__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_3_2_1(), "rule__Matrix__Group_2_3_2_1__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_3_2_1_2(), "rule__Matrix__Group_2_3_2_1_2__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_4(), "rule__Matrix__Group_2_4__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_4_2_0(), "rule__Matrix__Group_2_4_2_0__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_4_2_0_1(), "rule__Matrix__Group_2_4_2_0_1__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_4_2_1(), "rule__Matrix__Group_2_4_2_1__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_4_2_1_2(), "rule__Matrix__Group_2_4_2_1_2__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_5(), "rule__Matrix__Group_2_5__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_5_3(), "rule__Matrix__Group_2_5_3__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_6(), "rule__Matrix__Group_2_6__0");
			builder.put(grammarAccess.getMatrixAccess().getGroup_2_6_3(), "rule__Matrix__Group_2_6_3__0");
			builder.put(grammarAccess.getIncludeAccess().getGroup(), "rule__Include__Group__0");
			builder.put(grammarAccess.getIncludeAccess().getGroup_2_0(), "rule__Include__Group_2_0__0");
			builder.put(grammarAccess.getIncludeAccess().getGroup_2_1(), "rule__Include__Group_2_1__0");
			builder.put(grammarAccess.getIncludeAccess().getGroup_2_2(), "rule__Include__Group_2_2__0");
			builder.put(grammarAccess.getExcludeAccess().getGroup(), "rule__Exclude__Group__0");
			builder.put(grammarAccess.getExcludeAccess().getGroup_2_0(), "rule__Exclude__Group_2_0__0");
			builder.put(grammarAccess.getExcludeAccess().getGroup_2_1(), "rule__Exclude__Group_2_1__0");
			builder.put(grammarAccess.getContainerAccess().getGroup(), "rule__Container__Group__0");
			builder.put(grammarAccess.getContainerAccess().getGroup_2(), "rule__Container__Group_2__0");
			builder.put(grammarAccess.getGithubActionsAccess().getNameAssignment_0_2(), "rule__GithubActions__NameAssignment_0_2");
			builder.put(grammarAccess.getGithubActionsAccess().getOnAssignment_1_2(), "rule__GithubActions__OnAssignment_1_2");
			builder.put(grammarAccess.getGithubActionsAccess().getConcurrencyAssignment_2_2(), "rule__GithubActions__ConcurrencyAssignment_2_2");
			builder.put(grammarAccess.getGithubActionsAccess().getJobsAssignment_3_3(), "rule__GithubActions__JobsAssignment_3_3");
			builder.put(grammarAccess.getGithubActionsAccess().getPermissionsAssignment_4_2(), "rule__GithubActions__PermissionsAssignment_4_2");
			builder.put(grammarAccess.getGithubActionsAccess().getEnvAssignment_5_2_1(), "rule__GithubActions__EnvAssignment_5_2_1");
			builder.put(grammarAccess.getKeyValuePairAccess().getKeyAssignment_0(), "rule__KeyValuePair__KeyAssignment_0");
			builder.put(grammarAccess.getKeyValuePairAccess().getValueAssignment_2(), "rule__KeyValuePair__ValueAssignment_2");
			builder.put(grammarAccess.getOnAccess().getPushAssignment_2_0_2(), "rule__On__PushAssignment_2_0_2");
			builder.put(grammarAccess.getOnAccess().getPullRequestAssignment_2_1_2(), "rule__On__PullRequestAssignment_2_1_2");
			builder.put(grammarAccess.getOnAccess().getPullRequestTargetAssignment_2_2_2(), "rule__On__PullRequestTargetAssignment_2_2_2");
			builder.put(grammarAccess.getOnAccess().getScheduleAssignment_2_3_2_1(), "rule__On__ScheduleAssignment_2_3_2_1");
			builder.put(grammarAccess.getOnAccess().getWorkflowDispatchAssignment_2_4_2(), "rule__On__WorkflowDispatchAssignment_2_4_2");
			builder.put(grammarAccess.getOnAccess().getWorkflowCallAssignment_2_5_2(), "rule__On__WorkflowCallAssignment_2_5_2");
			builder.put(grammarAccess.getPushAccess().getBranchesAssignment_2_0_2_0_1_2(), "rule__Push__BranchesAssignment_2_0_2_0_1_2");
			builder.put(grammarAccess.getPushAccess().getBranchesAssignment_2_0_2_1_1(), "rule__Push__BranchesAssignment_2_0_2_1_1");
			builder.put(grammarAccess.getPushAccess().getBranchesAssignment_2_0_2_1_2_1(), "rule__Push__BranchesAssignment_2_0_2_1_2_1");
			builder.put(grammarAccess.getPushAccess().getTagsAssignment_2_1_2_0_1_2(), "rule__Push__TagsAssignment_2_1_2_0_1_2");
			builder.put(grammarAccess.getPushAccess().getTagsAssignment_2_1_2_1_1(), "rule__Push__TagsAssignment_2_1_2_1_1");
			builder.put(grammarAccess.getPushAccess().getTagsAssignment_2_1_2_1_2_1(), "rule__Push__TagsAssignment_2_1_2_1_2_1");
			builder.put(grammarAccess.getPull_requestAccess().getBranchesAssignment_2_0_2_0_1_2(), "rule__Pull_request__BranchesAssignment_2_0_2_0_1_2");
			builder.put(grammarAccess.getPull_requestAccess().getBranchesAssignment_2_0_2_1_1(), "rule__Pull_request__BranchesAssignment_2_0_2_1_1");
			builder.put(grammarAccess.getPull_requestAccess().getBranchesAssignment_2_0_2_1_2_1(), "rule__Pull_request__BranchesAssignment_2_0_2_1_2_1");
			builder.put(grammarAccess.getPull_requestAccess().getTypesAssignment_2_1_2_0_1_2(), "rule__Pull_request__TypesAssignment_2_1_2_0_1_2");
			builder.put(grammarAccess.getPull_requestAccess().getTypesAssignment_2_1_2_1_1(), "rule__Pull_request__TypesAssignment_2_1_2_1_1");
			builder.put(grammarAccess.getPull_requestAccess().getTypesAssignment_2_1_2_1_2_1(), "rule__Pull_request__TypesAssignment_2_1_2_1_2_1");
			builder.put(grammarAccess.getScheduleAccess().getCronAssignment_4(), "rule__Schedule__CronAssignment_4");
			builder.put(grammarAccess.getWorkflow_callAccess().getSecretsAssignment_2_3(), "rule__Workflow_call__SecretsAssignment_2_3");
			builder.put(grammarAccess.getSecretAccess().getIdAssignment_0(), "rule__Secret__IdAssignment_0");
			builder.put(grammarAccess.getSecretAccess().getRequiredAssignment_3_2(), "rule__Secret__RequiredAssignment_3_2");
			builder.put(grammarAccess.getConcurrencyAccess().getGroupAssignment_2_0_2(), "rule__Concurrency__GroupAssignment_2_0_2");
			builder.put(grammarAccess.getConcurrencyAccess().getCancelInProgressAssignment_2_1_2(), "rule__Concurrency__CancelInProgressAssignment_2_1_2");
			builder.put(grammarAccess.getEnvironmentAccess().getNameAssignment_2_0_2(), "rule__Environment__NameAssignment_2_0_2");
			builder.put(grammarAccess.getEnvironmentAccess().getUrlAssignment_2_1_2(), "rule__Environment__UrlAssignment_2_1_2");
			builder.put(grammarAccess.getPermissionsAccess().getContentsAssignment_2_0_2(), "rule__Permissions__ContentsAssignment_2_0_2");
			builder.put(grammarAccess.getPermissionsAccess().getSecurityEventsAssignment_2_1_2(), "rule__Permissions__SecurityEventsAssignment_2_1_2");
			builder.put(grammarAccess.getPermissionsAccess().getActionsAssignment_2_2_2(), "rule__Permissions__ActionsAssignment_2_2_2");
			builder.put(grammarAccess.getPermissionsAccess().getPagesAssignment_2_3_2(), "rule__Permissions__PagesAssignment_2_3_2");
			builder.put(grammarAccess.getPermissionsAccess().getIdTokenAssignment_2_4_2(), "rule__Permissions__IdTokenAssignment_2_4_2");
			builder.put(grammarAccess.getPermissionsAccess().getPullRequestsAssignment_2_5_2(), "rule__Permissions__PullRequestsAssignment_2_5_2");
			builder.put(grammarAccess.getPermissionsAccess().getIssuesAssignment_2_6_2(), "rule__Permissions__IssuesAssignment_2_6_2");
			builder.put(grammarAccess.getPermissionsAccess().getPackagesAssignment_2_7_2(), "rule__Permissions__PackagesAssignment_2_7_2");
			builder.put(grammarAccess.getJobAccess().getIdAssignment_0(), "rule__Job__IdAssignment_0");
			builder.put(grammarAccess.getJobAccess().getNameAssignment_3_0_2(), "rule__Job__NameAssignment_3_0_2");
			builder.put(grammarAccess.getJobAccess().getRunsOnAssignment_3_1_2(), "rule__Job__RunsOnAssignment_3_1_2");
			builder.put(grammarAccess.getJobAccess().getNeedsAssignment_3_2_2_0(), "rule__Job__NeedsAssignment_3_2_2_0");
			builder.put(grammarAccess.getJobAccess().getNeedsAssignment_3_2_2_1_1_2(), "rule__Job__NeedsAssignment_3_2_2_1_1_2");
			builder.put(grammarAccess.getJobAccess().getNeedsAssignment_3_2_2_2_1(), "rule__Job__NeedsAssignment_3_2_2_2_1");
			builder.put(grammarAccess.getJobAccess().getNeedsAssignment_3_2_2_2_2_1(), "rule__Job__NeedsAssignment_3_2_2_2_2_1");
			builder.put(grammarAccess.getJobAccess().getIfAssignment_3_3_2(), "rule__Job__IfAssignment_3_3_2");
			builder.put(grammarAccess.getJobAccess().getEnvironmentAssignment_3_4_2(), "rule__Job__EnvironmentAssignment_3_4_2");
			builder.put(grammarAccess.getJobAccess().getStrategyAssignment_3_5_2(), "rule__Job__StrategyAssignment_3_5_2");
			builder.put(grammarAccess.getJobAccess().getContainerAssignment_3_6_2(), "rule__Job__ContainerAssignment_3_6_2");
			builder.put(grammarAccess.getJobAccess().getStepsAssignment_3_7_3(), "rule__Job__StepsAssignment_3_7_3");
			builder.put(grammarAccess.getJobAccess().getPermissionsAssignment_3_8_2(), "rule__Job__PermissionsAssignment_3_8_2");
			builder.put(grammarAccess.getStepAccess().getNameAssignment_3_0_2(), "rule__Step__NameAssignment_3_0_2");
			builder.put(grammarAccess.getStepAccess().getIdAssignment_3_1_2(), "rule__Step__IdAssignment_3_1_2");
			builder.put(grammarAccess.getStepAccess().getUsesAssignment_3_2_2(), "rule__Step__UsesAssignment_3_2_2");
			builder.put(grammarAccess.getStepAccess().getRunAssignment_3_3_2(), "rule__Step__RunAssignment_3_3_2");
			builder.put(grammarAccess.getStepAccess().getIfAssignment_3_4_2(), "rule__Step__IfAssignment_3_4_2");
			builder.put(grammarAccess.getStepAccess().getWorkingDirectoryAssignment_3_5_2(), "rule__Step__WorkingDirectoryAssignment_3_5_2");
			builder.put(grammarAccess.getStepAccess().getShellAssignment_3_6_2(), "rule__Step__ShellAssignment_3_6_2");
			builder.put(grammarAccess.getStepAccess().getContinueOnErrorAssignment_3_7_2(), "rule__Step__ContinueOnErrorAssignment_3_7_2");
			builder.put(grammarAccess.getStepAccess().getWithAssignment_3_8_2_1(), "rule__Step__WithAssignment_3_8_2_1");
			builder.put(grammarAccess.getStepAccess().getEnvAssignment_3_9_2_1(), "rule__Step__EnvAssignment_3_9_2_1");
			builder.put(grammarAccess.getStrategyAccess().getFailFastAssignment_2_0_2(), "rule__Strategy__FailFastAssignment_2_0_2");
			builder.put(grammarAccess.getStrategyAccess().getMatrixAssignment_2_1_2(), "rule__Strategy__MatrixAssignment_2_1_2");
			builder.put(grammarAccess.getMatrixAccess().getOsAssignment_2_0_2_0_1_2(), "rule__Matrix__OsAssignment_2_0_2_0_1_2");
			builder.put(grammarAccess.getMatrixAccess().getOsAssignment_2_0_2_1_1(), "rule__Matrix__OsAssignment_2_0_2_1_1");
			builder.put(grammarAccess.getMatrixAccess().getOsAssignment_2_0_2_1_2_1(), "rule__Matrix__OsAssignment_2_0_2_1_2_1");
			builder.put(grammarAccess.getMatrixAccess().getBuildTypeAssignment_2_1_2_0_1_2(), "rule__Matrix__BuildTypeAssignment_2_1_2_0_1_2");
			builder.put(grammarAccess.getMatrixAccess().getBuildTypeAssignment_2_1_2_1_1(), "rule__Matrix__BuildTypeAssignment_2_1_2_1_1");
			builder.put(grammarAccess.getMatrixAccess().getBuildTypeAssignment_2_1_2_1_2_1(), "rule__Matrix__BuildTypeAssignment_2_1_2_1_2_1");
			builder.put(grammarAccess.getMatrixAccess().getCCompilerAssignment_2_2_2_0_1_2(), "rule__Matrix__CCompilerAssignment_2_2_2_0_1_2");
			builder.put(grammarAccess.getMatrixAccess().getCCompilerAssignment_2_2_2_1_1(), "rule__Matrix__CCompilerAssignment_2_2_2_1_1");
			builder.put(grammarAccess.getMatrixAccess().getCCompilerAssignment_2_2_2_1_2_1(), "rule__Matrix__CCompilerAssignment_2_2_2_1_2_1");
			builder.put(grammarAccess.getMatrixAccess().getOtpAssignment_2_3_2_0_1_2(), "rule__Matrix__OtpAssignment_2_3_2_0_1_2");
			builder.put(grammarAccess.getMatrixAccess().getOtpAssignment_2_3_2_1_1(), "rule__Matrix__OtpAssignment_2_3_2_1_1");
			builder.put(grammarAccess.getMatrixAccess().getOtpAssignment_2_3_2_1_2_1(), "rule__Matrix__OtpAssignment_2_3_2_1_2_1");
			builder.put(grammarAccess.getMatrixAccess().getElixirAssignment_2_4_2_0_1_2(), "rule__Matrix__ElixirAssignment_2_4_2_0_1_2");
			builder.put(grammarAccess.getMatrixAccess().getElixirAssignment_2_4_2_1_1(), "rule__Matrix__ElixirAssignment_2_4_2_1_1");
			builder.put(grammarAccess.getMatrixAccess().getElixirAssignment_2_4_2_1_2_1(), "rule__Matrix__ElixirAssignment_2_4_2_1_2_1");
			builder.put(grammarAccess.getMatrixAccess().getIncludeAssignment_2_5_3_2(), "rule__Matrix__IncludeAssignment_2_5_3_2");
			builder.put(grammarAccess.getMatrixAccess().getExcludeAssignment_2_6_3_2(), "rule__Matrix__ExcludeAssignment_2_6_3_2");
			builder.put(grammarAccess.getIncludeAccess().getOsAssignment_2_0_2(), "rule__Include__OsAssignment_2_0_2");
			builder.put(grammarAccess.getIncludeAccess().getCCompilerAssignment_2_1_2(), "rule__Include__CCompilerAssignment_2_1_2");
			builder.put(grammarAccess.getIncludeAccess().getCppCompilerAssignment_2_2_2(), "rule__Include__CppCompilerAssignment_2_2_2");
			builder.put(grammarAccess.getExcludeAccess().getOsAssignment_2_0_2(), "rule__Exclude__OsAssignment_2_0_2");
			builder.put(grammarAccess.getExcludeAccess().getCCompilerAssignment_2_1_2(), "rule__Exclude__CCompilerAssignment_2_1_2");
			builder.put(grammarAccess.getContainerAccess().getImageAssignment_2_2(), "rule__Container__ImageAssignment_2_2");
			builder.put(grammarAccess.getGithubActionsAccess().getUnorderedGroup(), "rule__GithubActions__UnorderedGroup");
			builder.put(grammarAccess.getOnAccess().getUnorderedGroup_2(), "rule__On__UnorderedGroup_2");
			builder.put(grammarAccess.getPushAccess().getUnorderedGroup_2(), "rule__Push__UnorderedGroup_2");
			builder.put(grammarAccess.getPull_requestAccess().getUnorderedGroup_2(), "rule__Pull_request__UnorderedGroup_2");
			builder.put(grammarAccess.getConcurrencyAccess().getUnorderedGroup_2(), "rule__Concurrency__UnorderedGroup_2");
			builder.put(grammarAccess.getEnvironmentAccess().getUnorderedGroup_2(), "rule__Environment__UnorderedGroup_2");
			builder.put(grammarAccess.getPermissionsAccess().getUnorderedGroup_2(), "rule__Permissions__UnorderedGroup_2");
			builder.put(grammarAccess.getJobAccess().getUnorderedGroup_3(), "rule__Job__UnorderedGroup_3");
			builder.put(grammarAccess.getStepAccess().getUnorderedGroup_3(), "rule__Step__UnorderedGroup_3");
			builder.put(grammarAccess.getStrategyAccess().getUnorderedGroup_2(), "rule__Strategy__UnorderedGroup_2");
			builder.put(grammarAccess.getMatrixAccess().getUnorderedGroup_2(), "rule__Matrix__UnorderedGroup_2");
			builder.put(grammarAccess.getIncludeAccess().getUnorderedGroup_2(), "rule__Include__UnorderedGroup_2");
			builder.put(grammarAccess.getExcludeAccess().getUnorderedGroup_2(), "rule__Exclude__UnorderedGroup_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MyDslGrammarAccess grammarAccess;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
