/*
 * generated by Xtext 2.42.0
 */
package pt.isep.yamldslgen.dockercompose.xtext.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import pt.isep.yamldslgen.dockercompose.xtext.ide.contentassist.antlr.internal.InternalDcDslParser;
import pt.isep.yamldslgen.dockercompose.xtext.services.DcDslGrammarAccess;

public class DcDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DcDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DcDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getDockerComposeAccess().getAlternatives(), "rule__DockerCompose__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getBlockStringAccess().getAlternatives_0(), "rule__BlockString__Alternatives_0");
			builder.put(grammarAccess.getBlockStringAccess().getAlternatives_2(), "rule__BlockString__Alternatives_2");
			builder.put(grammarAccess.getReservedWordAccess().getAlternatives(), "rule__ReservedWord__Alternatives");
			builder.put(grammarAccess.getKeyNameAccess().getAlternatives(), "rule__KeyName__Alternatives");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3(), "rule__Service__Alternatives_3");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_11_2(), "rule__Service__Alternatives_3_11_2");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_12_2(), "rule__Service__Alternatives_3_12_2");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_13_2(), "rule__Service__Alternatives_3_13_2");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_14_2(), "rule__Service__Alternatives_3_14_2");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_15_2(), "rule__Service__Alternatives_3_15_2");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_16_2(), "rule__Service__Alternatives_3_16_2");
			builder.put(grammarAccess.getServiceAccess().getAlternatives_3_17_2(), "rule__Service__Alternatives_3_17_2");
			builder.put(grammarAccess.getServiceVolumeAccess().getAlternatives_2(), "rule__ServiceVolume__Alternatives_2");
			builder.put(grammarAccess.getServiceVolumeAccess().getAlternatives_2_1_1(), "rule__ServiceVolume__Alternatives_2_1_1");
			builder.put(grammarAccess.getBuildAccess().getAlternatives(), "rule__Build__Alternatives");
			builder.put(grammarAccess.getBuildObjectAccess().getAlternatives_2(), "rule__BuildObject__Alternatives_2");
			builder.put(grammarAccess.getBuildObjectAccess().getAlternatives_2_3_2(), "rule__BuildObject__Alternatives_2_3_2");
			builder.put(grammarAccess.getNetworksAccess().getAlternatives(), "rule__Networks__Alternatives");
			builder.put(grammarAccess.getNetworksValueAccess().getAlternatives(), "rule__NetworksValue__Alternatives");
			builder.put(grammarAccess.getNetworkAccess().getAlternatives_3(), "rule__Network__Alternatives_3");
			builder.put(grammarAccess.getDepends_onAccess().getAlternatives(), "rule__Depends_on__Alternatives");
			builder.put(grammarAccess.getDepends_onValueAccess().getAlternatives(), "rule__Depends_onValue__Alternatives");
			builder.put(grammarAccess.getHealthcheckAccess().getAlternatives_2(), "rule__Healthcheck__Alternatives_2");
			builder.put(grammarAccess.getHealthcheckAccess().getAlternatives_2_0_2(), "rule__Healthcheck__Alternatives_2_0_2");
			builder.put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_0(), "rule__DockerCompose__Group_0__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_1(), "rule__DockerCompose__Group_1__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_2(), "rule__DockerCompose__Group_2__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_3(), "rule__DockerCompose__Group_3__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_4(), "rule__DockerCompose__Group_4__0");
			builder.put(grammarAccess.getDockerComposeAccess().getGroup_5(), "rule__DockerCompose__Group_5__0");
			builder.put(grammarAccess.getBlockStringAccess().getGroup(), "rule__BlockString__Group__0");
			builder.put(grammarAccess.getKeyValuePairAccess().getGroup(), "rule__KeyValuePair__Group__0");
			builder.put(grammarAccess.getServiceAccess().getGroup(), "rule__Service__Group__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_0(), "rule__Service__Group_3_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_1(), "rule__Service__Group_3_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_2(), "rule__Service__Group_3_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_3(), "rule__Service__Group_3_3__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_4(), "rule__Service__Group_3_4__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_5(), "rule__Service__Group_3_5__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_6(), "rule__Service__Group_3_6__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_7(), "rule__Service__Group_3_7__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_8(), "rule__Service__Group_3_8__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_9(), "rule__Service__Group_3_9__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_10(), "rule__Service__Group_3_10__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_11(), "rule__Service__Group_3_11__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_11_2_0(), "rule__Service__Group_3_11_2_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_11_2_0_1(), "rule__Service__Group_3_11_2_0_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_11_2_1(), "rule__Service__Group_3_11_2_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_11_2_1_2(), "rule__Service__Group_3_11_2_1_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_12(), "rule__Service__Group_3_12__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_12_2_0(), "rule__Service__Group_3_12_2_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_12_2_0_1(), "rule__Service__Group_3_12_2_0_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_12_2_1(), "rule__Service__Group_3_12_2_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_12_2_1_2(), "rule__Service__Group_3_12_2_1_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_13(), "rule__Service__Group_3_13__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_13_2_0(), "rule__Service__Group_3_13_2_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_13_2_0_1(), "rule__Service__Group_3_13_2_0_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_13_2_1(), "rule__Service__Group_3_13_2_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_13_2_1_2(), "rule__Service__Group_3_13_2_1_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_14(), "rule__Service__Group_3_14__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_14_2_0(), "rule__Service__Group_3_14_2_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_14_2_0_1(), "rule__Service__Group_3_14_2_0_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_14_2_1(), "rule__Service__Group_3_14_2_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_14_2_1_2(), "rule__Service__Group_3_14_2_1_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_15(), "rule__Service__Group_3_15__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_15_2_0(), "rule__Service__Group_3_15_2_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_15_2_0_1(), "rule__Service__Group_3_15_2_0_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_15_2_1(), "rule__Service__Group_3_15_2_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_15_2_1_2(), "rule__Service__Group_3_15_2_1_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_16(), "rule__Service__Group_3_16__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_16_2_0(), "rule__Service__Group_3_16_2_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_16_2_0_1(), "rule__Service__Group_3_16_2_0_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_16_2_1(), "rule__Service__Group_3_16_2_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_16_2_1_2(), "rule__Service__Group_3_16_2_1_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_17(), "rule__Service__Group_3_17__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_17_2_0(), "rule__Service__Group_3_17_2_0__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_17_2_0_1(), "rule__Service__Group_3_17_2_0_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_17_2_1(), "rule__Service__Group_3_17_2_1__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_17_2_1_2(), "rule__Service__Group_3_17_2_1_2__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_18(), "rule__Service__Group_3_18__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_19(), "rule__Service__Group_3_19__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_20(), "rule__Service__Group_3_20__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_21(), "rule__Service__Group_3_21__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_22(), "rule__Service__Group_3_22__0");
			builder.put(grammarAccess.getServiceAccess().getGroup_3_23(), "rule__Service__Group_3_23__0");
			builder.put(grammarAccess.getServiceVolumeAccess().getGroup(), "rule__ServiceVolume__Group__0");
			builder.put(grammarAccess.getServiceVolumeAccess().getGroup_2_0(), "rule__ServiceVolume__Group_2_0__0");
			builder.put(grammarAccess.getServiceVolumeAccess().getGroup_2_1(), "rule__ServiceVolume__Group_2_1__0");
			builder.put(grammarAccess.getServiceVolumeAccess().getGroup_2_1_1_0(), "rule__ServiceVolume__Group_2_1_1_0__0");
			builder.put(grammarAccess.getServiceVolumeAccess().getGroup_2_1_1_1(), "rule__ServiceVolume__Group_2_1_1_1__0");
			builder.put(grammarAccess.getServiceVolumeAccess().getGroup_2_1_1_2(), "rule__ServiceVolume__Group_2_1_1_2__0");
			builder.put(grammarAccess.getServiceVolumeAccess().getGroup_2_1_1_3(), "rule__ServiceVolume__Group_2_1_1_3__0");
			builder.put(grammarAccess.getNamedVolumeAccess().getGroup(), "rule__NamedVolume__Group__0");
			builder.put(grammarAccess.getBuildObjectAccess().getGroup(), "rule__BuildObject__Group__0");
			builder.put(grammarAccess.getBuildObjectAccess().getGroup_2_0(), "rule__BuildObject__Group_2_0__0");
			builder.put(grammarAccess.getBuildObjectAccess().getGroup_2_1(), "rule__BuildObject__Group_2_1__0");
			builder.put(grammarAccess.getBuildObjectAccess().getGroup_2_2(), "rule__BuildObject__Group_2_2__0");
			builder.put(grammarAccess.getBuildObjectAccess().getGroup_2_3(), "rule__BuildObject__Group_2_3__0");
			builder.put(grammarAccess.getBuildObjectAccess().getGroup_2_3_2_0(), "rule__BuildObject__Group_2_3_2_0__0");
			builder.put(grammarAccess.getBuildObjectAccess().getGroup_2_3_2_0_1(), "rule__BuildObject__Group_2_3_2_0_1__0");
			builder.put(grammarAccess.getBuildObjectAccess().getGroup_2_3_2_1(), "rule__BuildObject__Group_2_3_2_1__0");
			builder.put(grammarAccess.getBuildObjectAccess().getGroup_2_3_2_1_2(), "rule__BuildObject__Group_2_3_2_1_2__0");
			builder.put(grammarAccess.getNetworksValueAccess().getGroup_1(), "rule__NetworksValue__Group_1__0");
			builder.put(grammarAccess.getNetworksValueAccess().getGroup_1_2(), "rule__NetworksValue__Group_1_2__0");
			builder.put(grammarAccess.getNetworksObjectAccess().getGroup(), "rule__NetworksObject__Group__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup(), "rule__Network__Group__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_0(), "rule__Network__Group_3_0__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_1(), "rule__Network__Group_3_1__0");
			builder.put(grammarAccess.getNetworkAccess().getGroup_3_2(), "rule__Network__Group_3_2__0");
			builder.put(grammarAccess.getConfigAccess().getGroup(), "rule__Config__Group__0");
			builder.put(grammarAccess.getConfigAccess().getGroup_2(), "rule__Config__Group_2__0");
			builder.put(grammarAccess.getDepends_onValueAccess().getGroup_1(), "rule__Depends_onValue__Group_1__0");
			builder.put(grammarAccess.getDepends_onValueAccess().getGroup_1_2(), "rule__Depends_onValue__Group_1_2__0");
			builder.put(grammarAccess.getDepends_onObjectAccess().getGroup(), "rule__Depends_onObject__Group__0");
			builder.put(grammarAccess.getDbAccess().getGroup(), "rule__Db__Group__0");
			builder.put(grammarAccess.getDbAccess().getGroup_4(), "rule__Db__Group_4__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup(), "rule__Healthcheck__Group__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_0(), "rule__Healthcheck__Group_2_0__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_0_2_0(), "rule__Healthcheck__Group_2_0_2_0__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_0_2_0_1(), "rule__Healthcheck__Group_2_0_2_0_1__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_0_2_1(), "rule__Healthcheck__Group_2_0_2_1__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_0_2_1_2(), "rule__Healthcheck__Group_2_0_2_1_2__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_1(), "rule__Healthcheck__Group_2_1__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_2(), "rule__Healthcheck__Group_2_2__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_3(), "rule__Healthcheck__Group_2_3__0");
			builder.put(grammarAccess.getHealthcheckAccess().getGroup_2_4(), "rule__Healthcheck__Group_2_4__0");
			builder.put(grammarAccess.getSecretAccess().getGroup(), "rule__Secret__Group__0");
			builder.put(grammarAccess.getSecretAccess().getGroup_3(), "rule__Secret__Group_3__0");
			builder.put(grammarAccess.getResourceAccess().getGroup(), "rule__Resource__Group__0");
			builder.put(grammarAccess.getResourceAccess().getGroup_3(), "rule__Resource__Group_3__0");
			builder.put(grammarAccess.getDockerComposeAccess().getVersionAssignment_0_2(), "rule__DockerCompose__VersionAssignment_0_2");
			builder.put(grammarAccess.getDockerComposeAccess().getNameAssignment_1_2(), "rule__DockerCompose__NameAssignment_1_2");
			builder.put(grammarAccess.getDockerComposeAccess().getServicesAssignment_2_3(), "rule__DockerCompose__ServicesAssignment_2_3");
			builder.put(grammarAccess.getDockerComposeAccess().getNetworksAssignment_3_2(), "rule__DockerCompose__NetworksAssignment_3_2");
			builder.put(grammarAccess.getDockerComposeAccess().getVolumesAssignment_4_3(), "rule__DockerCompose__VolumesAssignment_4_3");
			builder.put(grammarAccess.getDockerComposeAccess().getSecretsAssignment_5_3(), "rule__DockerCompose__SecretsAssignment_5_3");
			builder.put(grammarAccess.getKeyValuePairAccess().getKeyAssignment_0(), "rule__KeyValuePair__KeyAssignment_0");
			builder.put(grammarAccess.getKeyValuePairAccess().getValueAssignment_2(), "rule__KeyValuePair__ValueAssignment_2");
			builder.put(grammarAccess.getServiceAccess().getIdAssignment_0(), "rule__Service__IdAssignment_0");
			builder.put(grammarAccess.getServiceAccess().getImageAssignment_3_0_2(), "rule__Service__ImageAssignment_3_0_2");
			builder.put(grammarAccess.getServiceAccess().getBuildAssignment_3_1_2(), "rule__Service__BuildAssignment_3_1_2");
			builder.put(grammarAccess.getServiceAccess().getContainerNameAssignment_3_2_2(), "rule__Service__ContainerNameAssignment_3_2_2");
			builder.put(grammarAccess.getServiceAccess().getRestartAssignment_3_3_2(), "rule__Service__RestartAssignment_3_3_2");
			builder.put(grammarAccess.getServiceAccess().getUserAssignment_3_4_2(), "rule__Service__UserAssignment_3_4_2");
			builder.put(grammarAccess.getServiceAccess().getHostnameAssignment_3_5_2(), "rule__Service__HostnameAssignment_3_5_2");
			builder.put(grammarAccess.getServiceAccess().getNetworkModeAssignment_3_6_2(), "rule__Service__NetworkModeAssignment_3_6_2");
			builder.put(grammarAccess.getServiceAccess().getPlatformAssignment_3_7_2(), "rule__Service__PlatformAssignment_3_7_2");
			builder.put(grammarAccess.getServiceAccess().getRuntimeAssignment_3_8_2(), "rule__Service__RuntimeAssignment_3_8_2");
			builder.put(grammarAccess.getServiceAccess().getStopSignalAssignment_3_9_2(), "rule__Service__StopSignalAssignment_3_9_2");
			builder.put(grammarAccess.getServiceAccess().getStdinOpenAssignment_3_10_2(), "rule__Service__StdinOpenAssignment_3_10_2");
			builder.put(grammarAccess.getServiceAccess().getPortsAssignment_3_11_2_0_1_1(), "rule__Service__PortsAssignment_3_11_2_0_1_1");
			builder.put(grammarAccess.getServiceAccess().getPortsAssignment_3_11_2_1_1(), "rule__Service__PortsAssignment_3_11_2_1_1");
			builder.put(grammarAccess.getServiceAccess().getPortsAssignment_3_11_2_1_2_1(), "rule__Service__PortsAssignment_3_11_2_1_2_1");
			builder.put(grammarAccess.getServiceAccess().getExposeAssignment_3_12_2_0_1_1(), "rule__Service__ExposeAssignment_3_12_2_0_1_1");
			builder.put(grammarAccess.getServiceAccess().getExposeAssignment_3_12_2_1_1(), "rule__Service__ExposeAssignment_3_12_2_1_1");
			builder.put(grammarAccess.getServiceAccess().getExposeAssignment_3_12_2_1_2_1(), "rule__Service__ExposeAssignment_3_12_2_1_2_1");
			builder.put(grammarAccess.getServiceAccess().getCommandAssignment_3_13_2_0_1_1(), "rule__Service__CommandAssignment_3_13_2_0_1_1");
			builder.put(grammarAccess.getServiceAccess().getCommandAssignment_3_13_2_1_1(), "rule__Service__CommandAssignment_3_13_2_1_1");
			builder.put(grammarAccess.getServiceAccess().getCommandAssignment_3_13_2_1_2_1(), "rule__Service__CommandAssignment_3_13_2_1_2_1");
			builder.put(grammarAccess.getServiceAccess().getSecretsAssignment_3_14_2_0_1_1(), "rule__Service__SecretsAssignment_3_14_2_0_1_1");
			builder.put(grammarAccess.getServiceAccess().getSecretsAssignment_3_14_2_1_1(), "rule__Service__SecretsAssignment_3_14_2_1_1");
			builder.put(grammarAccess.getServiceAccess().getSecretsAssignment_3_14_2_1_2_1(), "rule__Service__SecretsAssignment_3_14_2_1_2_1");
			builder.put(grammarAccess.getServiceAccess().getCapAddAssignment_3_15_2_0_1_1(), "rule__Service__CapAddAssignment_3_15_2_0_1_1");
			builder.put(grammarAccess.getServiceAccess().getCapAddAssignment_3_15_2_1_1(), "rule__Service__CapAddAssignment_3_15_2_1_1");
			builder.put(grammarAccess.getServiceAccess().getCapAddAssignment_3_15_2_1_2_1(), "rule__Service__CapAddAssignment_3_15_2_1_2_1");
			builder.put(grammarAccess.getServiceAccess().getLabelsAssignment_3_16_2_0_1_1(), "rule__Service__LabelsAssignment_3_16_2_0_1_1");
			builder.put(grammarAccess.getServiceAccess().getLabelsAssignment_3_16_2_1_1(), "rule__Service__LabelsAssignment_3_16_2_1_1");
			builder.put(grammarAccess.getServiceAccess().getLabelsAssignment_3_16_2_1_2_1(), "rule__Service__LabelsAssignment_3_16_2_1_2_1");
			builder.put(grammarAccess.getServiceAccess().getSysctlsAssignment_3_17_2_0_1_1(), "rule__Service__SysctlsAssignment_3_17_2_0_1_1");
			builder.put(grammarAccess.getServiceAccess().getSysctlsAssignment_3_17_2_1_1(), "rule__Service__SysctlsAssignment_3_17_2_1_1");
			builder.put(grammarAccess.getServiceAccess().getSysctlsAssignment_3_17_2_1_2_1(), "rule__Service__SysctlsAssignment_3_17_2_1_2_1");
			builder.put(grammarAccess.getServiceAccess().getEnvironmentAssignment_3_18_3(), "rule__Service__EnvironmentAssignment_3_18_3");
			builder.put(grammarAccess.getServiceAccess().getDependsOnAssignment_3_19_2(), "rule__Service__DependsOnAssignment_3_19_2");
			builder.put(grammarAccess.getServiceAccess().getNetworksAssignment_3_20_2(), "rule__Service__NetworksAssignment_3_20_2");
			builder.put(grammarAccess.getServiceAccess().getVolumesAssignment_3_21_3(), "rule__Service__VolumesAssignment_3_21_3");
			builder.put(grammarAccess.getServiceAccess().getHealthcheckAssignment_3_22_2(), "rule__Service__HealthcheckAssignment_3_22_2");
			builder.put(grammarAccess.getServiceAccess().getDeployAssignment_3_23_3(), "rule__Service__DeployAssignment_3_23_3");
			builder.put(grammarAccess.getServiceVolumeAccess().getValueAssignment_2_0_1(), "rule__ServiceVolume__ValueAssignment_2_0_1");
			builder.put(grammarAccess.getServiceVolumeAccess().getTypeAssignment_2_1_1_0_2(), "rule__ServiceVolume__TypeAssignment_2_1_1_0_2");
			builder.put(grammarAccess.getServiceVolumeAccess().getSourceAssignment_2_1_1_1_2(), "rule__ServiceVolume__SourceAssignment_2_1_1_1_2");
			builder.put(grammarAccess.getServiceVolumeAccess().getTargetAssignment_2_1_1_2_2(), "rule__ServiceVolume__TargetAssignment_2_1_1_2_2");
			builder.put(grammarAccess.getServiceVolumeAccess().getReadOnlyAssignment_2_1_1_3_2(), "rule__ServiceVolume__ReadOnlyAssignment_2_1_1_3_2");
			builder.put(grammarAccess.getNamedVolumeAccess().getIdAssignment_0(), "rule__NamedVolume__IdAssignment_0");
			builder.put(grammarAccess.getBuildValueAccess().getValueAssignment(), "rule__BuildValue__ValueAssignment");
			builder.put(grammarAccess.getBuildObjectAccess().getContextAssignment_2_0_2(), "rule__BuildObject__ContextAssignment_2_0_2");
			builder.put(grammarAccess.getBuildObjectAccess().getDockerfileAssignment_2_1_2(), "rule__BuildObject__DockerfileAssignment_2_1_2");
			builder.put(grammarAccess.getBuildObjectAccess().getTargetAssignment_2_2_2(), "rule__BuildObject__TargetAssignment_2_2_2");
			builder.put(grammarAccess.getBuildObjectAccess().getArgsAssignment_2_3_2_0_1_1(), "rule__BuildObject__ArgsAssignment_2_3_2_0_1_1");
			builder.put(grammarAccess.getBuildObjectAccess().getArgsAssignment_2_3_2_1_1(), "rule__BuildObject__ArgsAssignment_2_3_2_1_1");
			builder.put(grammarAccess.getBuildObjectAccess().getArgsAssignment_2_3_2_1_2_1(), "rule__BuildObject__ArgsAssignment_2_3_2_1_2_1");
			builder.put(grammarAccess.getNetworksValueAccess().getValueAssignment_0(), "rule__NetworksValue__ValueAssignment_0");
			builder.put(grammarAccess.getNetworksValueAccess().getValueAssignment_1_1(), "rule__NetworksValue__ValueAssignment_1_1");
			builder.put(grammarAccess.getNetworksValueAccess().getValueAssignment_1_2_1(), "rule__NetworksValue__ValueAssignment_1_2_1");
			builder.put(grammarAccess.getNetworksObjectAccess().getNetworkAssignment_2(), "rule__NetworksObject__NetworkAssignment_2");
			builder.put(grammarAccess.getNetworkAccess().getIdAssignment_0(), "rule__Network__IdAssignment_0");
			builder.put(grammarAccess.getNetworkAccess().getDriverAssignment_3_0_2(), "rule__Network__DriverAssignment_3_0_2");
			builder.put(grammarAccess.getNetworkAccess().getIpv4AddressAssignment_3_1_2(), "rule__Network__Ipv4AddressAssignment_3_1_2");
			builder.put(grammarAccess.getNetworkAccess().getIpamAssignment_3_2_3(), "rule__Network__IpamAssignment_3_2_3");
			builder.put(grammarAccess.getConfigAccess().getSubnetAssignment_2_2(), "rule__Config__SubnetAssignment_2_2");
			builder.put(grammarAccess.getDepends_onValueAccess().getValueAssignment_0(), "rule__Depends_onValue__ValueAssignment_0");
			builder.put(grammarAccess.getDepends_onValueAccess().getValueAssignment_1_1(), "rule__Depends_onValue__ValueAssignment_1_1");
			builder.put(grammarAccess.getDepends_onValueAccess().getValueAssignment_1_2_1(), "rule__Depends_onValue__ValueAssignment_1_2_1");
			builder.put(grammarAccess.getDepends_onObjectAccess().getDbAssignment_2(), "rule__Depends_onObject__DbAssignment_2");
			builder.put(grammarAccess.getDbAccess().getConditionAssignment_4_2(), "rule__Db__ConditionAssignment_4_2");
			builder.put(grammarAccess.getHealthcheckAccess().getTestAssignment_2_0_2_0_1_1(), "rule__Healthcheck__TestAssignment_2_0_2_0_1_1");
			builder.put(grammarAccess.getHealthcheckAccess().getTestAssignment_2_0_2_1_1(), "rule__Healthcheck__TestAssignment_2_0_2_1_1");
			builder.put(grammarAccess.getHealthcheckAccess().getTestAssignment_2_0_2_1_2_1(), "rule__Healthcheck__TestAssignment_2_0_2_1_2_1");
			builder.put(grammarAccess.getHealthcheckAccess().getIntervalAssignment_2_1_2(), "rule__Healthcheck__IntervalAssignment_2_1_2");
			builder.put(grammarAccess.getHealthcheckAccess().getTimeoutAssignment_2_2_2(), "rule__Healthcheck__TimeoutAssignment_2_2_2");
			builder.put(grammarAccess.getHealthcheckAccess().getRetriesAssignment_2_3_2(), "rule__Healthcheck__RetriesAssignment_2_3_2");
			builder.put(grammarAccess.getHealthcheckAccess().getStartPeriodAssignment_2_4_2(), "rule__Healthcheck__StartPeriodAssignment_2_4_2");
			builder.put(grammarAccess.getSecretAccess().getIdAssignment_0(), "rule__Secret__IdAssignment_0");
			builder.put(grammarAccess.getSecretAccess().getFileAssignment_3_2(), "rule__Secret__FileAssignment_3_2");
			builder.put(grammarAccess.getResourceAccess().getIdAssignment_0(), "rule__Resource__IdAssignment_0");
			builder.put(grammarAccess.getResourceAccess().getMemoryAssignment_3_2(), "rule__Resource__MemoryAssignment_3_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DcDslGrammarAccess grammarAccess;

	@Override
	protected InternalDcDslParser createParser() {
		InternalDcDslParser result = new InternalDcDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DcDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DcDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
