/**
 * generated by Xtext 2.42.0
 */
package pt.isep.yamldslgen.dockercompose.xtext.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import pt.isep.yamldslgen.docker_compose.Build;
import pt.isep.yamldslgen.docker_compose.Depends_on;
import pt.isep.yamldslgen.docker_compose.DockerCompose;
import pt.isep.yamldslgen.docker_compose.Healthcheck;
import pt.isep.yamldslgen.docker_compose.KeyValuePair;
import pt.isep.yamldslgen.docker_compose.Networks;
import pt.isep.yamldslgen.docker_compose.Resource;
import pt.isep.yamldslgen.docker_compose.Secret;
import pt.isep.yamldslgen.docker_compose.Service;
import pt.isep.yamldslgen.docker_compose.Volume;
import pt.isep.yamldslgen.dockercompose.xtext.services.DcDslGrammarAccess;

@SuppressWarnings("all")
public class DcDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private DcDslGrammarAccess _dcDslGrammarAccess;

  protected void _format(final DockerCompose dockerCompose, @Extension final IFormattableDocument document) {
    EList<Service> _services = dockerCompose.getServices();
    for (final Service service : _services) {
      document.<Service>format(service);
    }
    document.<Networks>format(dockerCompose.getNetworks());
    EList<Volume> _volumes = dockerCompose.getVolumes();
    for (final Volume volume : _volumes) {
      document.<Volume>format(volume);
    }
    EList<Secret> _secrets = dockerCompose.getSecrets();
    for (final Secret secret : _secrets) {
      document.<Secret>format(secret);
    }
  }

  protected void _format(final Service service, @Extension final IFormattableDocument document) {
    document.<Build>format(service.getBuild());
    document.<Healthcheck>format(service.getHealthcheck());
    EList<Resource> _deploy = service.getDeploy();
    for (final Resource resource : _deploy) {
      document.<Resource>format(resource);
    }
    document.<Depends_on>format(service.getDependsOn());
    EList<Volume> _volumes = service.getVolumes();
    for (final Volume volume : _volumes) {
      document.<Volume>format(volume);
    }
    document.<Networks>format(service.getNetworks());
    EList<KeyValuePair> _environment = service.getEnvironment();
    for (final KeyValuePair keyValuePair : _environment) {
      document.<KeyValuePair>format(keyValuePair);
    }
  }

  @XbaseGenerated
  public void format(final Object dockerCompose, final IFormattableDocument document) {
    if (dockerCompose instanceof XtextResource) {
      _format((XtextResource)dockerCompose, document);
      return;
    } else if (dockerCompose instanceof DockerCompose) {
      _format((DockerCompose)dockerCompose, document);
      return;
    } else if (dockerCompose instanceof Service) {
      _format((Service)dockerCompose, document);
      return;
    } else if (dockerCompose instanceof EObject) {
      _format((EObject)dockerCompose, document);
      return;
    } else if (dockerCompose == null) {
      _format((Void)null, document);
      return;
    } else if (dockerCompose != null) {
      _format(dockerCompose, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(dockerCompose, document).toString());
    }
  }
}
