/*
 * generated by Xtext 2.42.0
 */
package pt.isep.yamldslgen.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import pt.isep.yamldslgen.xtext.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MyDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Concurrency_BEG_BLOCKTerminalRuleCall_1_q;
	protected AbstractElementAlias match_Concurrency_END_BLOCKTerminalRuleCall_3_q;
	protected AbstractElementAlias match_Environment_BEG_BLOCKTerminalRuleCall_1_q;
	protected AbstractElementAlias match_Environment_END_BLOCKTerminalRuleCall_3_q;
	protected AbstractElementAlias match_GithubActions_BEG_BLOCKTerminalRuleCall_3_2_q;
	protected AbstractElementAlias match_GithubActions_BEG_BLOCKTerminalRuleCall_4_2_0_q;
	protected AbstractElementAlias match_GithubActions_BEG_BLOCKTerminalRuleCall_5_2_0_q;
	protected AbstractElementAlias match_GithubActions_END_BLOCKTerminalRuleCall_3_4_q;
	protected AbstractElementAlias match_GithubActions_END_BLOCKTerminalRuleCall_4_2_2_q;
	protected AbstractElementAlias match_GithubActions_END_BLOCKTerminalRuleCall_5_2_2_q;
	protected AbstractElementAlias match_GithubActions___END_BLOCKTerminalRuleCall_3_4_q_JobsKeyword_3_0_ColonKeyword_3_1_BEG_BLOCKTerminalRuleCall_3_2_q__q;
	protected AbstractElementAlias match_GithubActions___END_BLOCKTerminalRuleCall_4_2_2_q_PermissionsKeyword_4_0_ColonKeyword_4_1_BEG_BLOCKTerminalRuleCall_4_2_0_q__q;
	protected AbstractElementAlias match_GithubActions___END_BLOCKTerminalRuleCall_5_2_2_q_EnvKeyword_5_0_ColonKeyword_5_1_BEG_BLOCKTerminalRuleCall_5_2_0_q__q;
	protected AbstractElementAlias match_Job_BEG_BLOCKTerminalRuleCall_2_q;
	protected AbstractElementAlias match_Job_BEG_BLOCKTerminalRuleCall_3_2_2_1_1_1_q;
	protected AbstractElementAlias match_Job_BEG_BLOCKTerminalRuleCall_3_4_2_q;
	protected AbstractElementAlias match_Job_BEG_BLOCKTerminalRuleCall_3_5_2_0_q;
	protected AbstractElementAlias match_Job_END_BLOCKTerminalRuleCall_3_2_2_1_1_3_q;
	protected AbstractElementAlias match_Job_END_BLOCKTerminalRuleCall_3_4_4_q;
	protected AbstractElementAlias match_Job_END_BLOCKTerminalRuleCall_3_5_2_2_q;
	protected AbstractElementAlias match_Job_END_BLOCKTerminalRuleCall_4_q;
	protected AbstractElementAlias match_Job___END_BLOCKTerminalRuleCall_3_2_2_1_2_NeedsKeyword_3_2_0_ColonKeyword_3_2_1_BEG_BLOCKTerminalRuleCall_3_2_2_1_0__q;
	protected AbstractElementAlias match_Job___END_BLOCKTerminalRuleCall_3_4_4_q_StepsKeyword_3_4_0_ColonKeyword_3_4_1_BEG_BLOCKTerminalRuleCall_3_4_2_q__q;
	protected AbstractElementAlias match_Job___END_BLOCKTerminalRuleCall_3_5_2_2_q_PermissionsKeyword_3_5_0_ColonKeyword_3_5_1_BEG_BLOCKTerminalRuleCall_3_5_2_0_q__q;
	protected AbstractElementAlias match_On_BEG_BLOCKTerminalRuleCall_1_q;
	protected AbstractElementAlias match_On_BEG_BLOCKTerminalRuleCall_2_2_2_0_q;
	protected AbstractElementAlias match_On_END_BLOCKTerminalRuleCall_2_2_2_2_q;
	protected AbstractElementAlias match_On_END_BLOCKTerminalRuleCall_3_q;
	protected AbstractElementAlias match_On___END_BLOCKTerminalRuleCall_2_2_2_2_q___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__a_ScheduleKeyword_2_2_0_ColonKeyword_2_2_1_BEG_BLOCKTerminalRuleCall_2_2_2_0_q__q;
	protected AbstractElementAlias match_On___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__a;
	protected AbstractElementAlias match_On___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__p;
	protected AbstractElementAlias match_Push___END_BLOCKTerminalRuleCall_2_0_2_0_2_BranchesKeyword_2_0_0_ColonKeyword_2_0_1_BEG_BLOCKTerminalRuleCall_2_0_2_0_0__q;
	protected AbstractElementAlias match_Push___END_BLOCKTerminalRuleCall_2_1_2_0_2_TagsKeyword_2_1_0_ColonKeyword_2_1_1_BEG_BLOCKTerminalRuleCall_2_1_2_0_0__q;
	protected AbstractElementAlias match_Schedule_BEG_BLOCKTerminalRuleCall_1_q;
	protected AbstractElementAlias match_Schedule_END_BLOCKTerminalRuleCall_5_q;
	protected AbstractElementAlias match_Step_BEG_BLOCKTerminalRuleCall_2_q;
	protected AbstractElementAlias match_Step_BEG_BLOCKTerminalRuleCall_3_6_2_0_q;
	protected AbstractElementAlias match_Step_BEG_BLOCKTerminalRuleCall_3_7_2_0_q;
	protected AbstractElementAlias match_Step_END_BLOCKTerminalRuleCall_3_6_2_2_q;
	protected AbstractElementAlias match_Step_END_BLOCKTerminalRuleCall_3_7_2_2_q;
	protected AbstractElementAlias match_Step_END_BLOCKTerminalRuleCall_4_q;
	protected AbstractElementAlias match_Step___END_BLOCKTerminalRuleCall_3_6_2_2_q_WithKeyword_3_6_0_ColonKeyword_3_6_1_BEG_BLOCKTerminalRuleCall_3_6_2_0_q__q;
	protected AbstractElementAlias match_Step___END_BLOCKTerminalRuleCall_3_7_2_2_q_EnvKeyword_3_7_0_ColonKeyword_3_7_1_BEG_BLOCKTerminalRuleCall_3_7_2_0_q__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MyDslGrammarAccess) access;
		match_Concurrency_BEG_BLOCKTerminalRuleCall_1_q = new TokenAlias(false, true, grammarAccess.getConcurrencyAccess().getBEG_BLOCKTerminalRuleCall_1());
		match_Concurrency_END_BLOCKTerminalRuleCall_3_q = new TokenAlias(false, true, grammarAccess.getConcurrencyAccess().getEND_BLOCKTerminalRuleCall_3());
		match_Environment_BEG_BLOCKTerminalRuleCall_1_q = new TokenAlias(false, true, grammarAccess.getEnvironmentAccess().getBEG_BLOCKTerminalRuleCall_1());
		match_Environment_END_BLOCKTerminalRuleCall_3_q = new TokenAlias(false, true, grammarAccess.getEnvironmentAccess().getEND_BLOCKTerminalRuleCall_3());
		match_GithubActions_BEG_BLOCKTerminalRuleCall_3_2_q = new TokenAlias(false, true, grammarAccess.getGithubActionsAccess().getBEG_BLOCKTerminalRuleCall_3_2());
		match_GithubActions_BEG_BLOCKTerminalRuleCall_4_2_0_q = new TokenAlias(false, true, grammarAccess.getGithubActionsAccess().getBEG_BLOCKTerminalRuleCall_4_2_0());
		match_GithubActions_BEG_BLOCKTerminalRuleCall_5_2_0_q = new TokenAlias(false, true, grammarAccess.getGithubActionsAccess().getBEG_BLOCKTerminalRuleCall_5_2_0());
		match_GithubActions_END_BLOCKTerminalRuleCall_3_4_q = new TokenAlias(false, true, grammarAccess.getGithubActionsAccess().getEND_BLOCKTerminalRuleCall_3_4());
		match_GithubActions_END_BLOCKTerminalRuleCall_4_2_2_q = new TokenAlias(false, true, grammarAccess.getGithubActionsAccess().getEND_BLOCKTerminalRuleCall_4_2_2());
		match_GithubActions_END_BLOCKTerminalRuleCall_5_2_2_q = new TokenAlias(false, true, grammarAccess.getGithubActionsAccess().getEND_BLOCKTerminalRuleCall_5_2_2());
		match_GithubActions___END_BLOCKTerminalRuleCall_3_4_q_JobsKeyword_3_0_ColonKeyword_3_1_BEG_BLOCKTerminalRuleCall_3_2_q__q = new GroupAlias(false, true, new TokenAlias(false, true, grammarAccess.getGithubActionsAccess().getEND_BLOCKTerminalRuleCall_3_4()), new TokenAlias(false, false, grammarAccess.getGithubActionsAccess().getJobsKeyword_3_0()), new TokenAlias(false, false, grammarAccess.getGithubActionsAccess().getColonKeyword_3_1()), new TokenAlias(false, true, grammarAccess.getGithubActionsAccess().getBEG_BLOCKTerminalRuleCall_3_2()));
		match_GithubActions___END_BLOCKTerminalRuleCall_4_2_2_q_PermissionsKeyword_4_0_ColonKeyword_4_1_BEG_BLOCKTerminalRuleCall_4_2_0_q__q = new GroupAlias(false, true, new TokenAlias(false, true, grammarAccess.getGithubActionsAccess().getEND_BLOCKTerminalRuleCall_4_2_2()), new TokenAlias(false, false, grammarAccess.getGithubActionsAccess().getPermissionsKeyword_4_0()), new TokenAlias(false, false, grammarAccess.getGithubActionsAccess().getColonKeyword_4_1()), new TokenAlias(false, true, grammarAccess.getGithubActionsAccess().getBEG_BLOCKTerminalRuleCall_4_2_0()));
		match_GithubActions___END_BLOCKTerminalRuleCall_5_2_2_q_EnvKeyword_5_0_ColonKeyword_5_1_BEG_BLOCKTerminalRuleCall_5_2_0_q__q = new GroupAlias(false, true, new TokenAlias(false, true, grammarAccess.getGithubActionsAccess().getEND_BLOCKTerminalRuleCall_5_2_2()), new TokenAlias(false, false, grammarAccess.getGithubActionsAccess().getEnvKeyword_5_0()), new TokenAlias(false, false, grammarAccess.getGithubActionsAccess().getColonKeyword_5_1()), new TokenAlias(false, true, grammarAccess.getGithubActionsAccess().getBEG_BLOCKTerminalRuleCall_5_2_0()));
		match_Job_BEG_BLOCKTerminalRuleCall_2_q = new TokenAlias(false, true, grammarAccess.getJobAccess().getBEG_BLOCKTerminalRuleCall_2());
		match_Job_BEG_BLOCKTerminalRuleCall_3_2_2_1_1_1_q = new TokenAlias(false, true, grammarAccess.getJobAccess().getBEG_BLOCKTerminalRuleCall_3_2_2_1_1_1());
		match_Job_BEG_BLOCKTerminalRuleCall_3_4_2_q = new TokenAlias(false, true, grammarAccess.getJobAccess().getBEG_BLOCKTerminalRuleCall_3_4_2());
		match_Job_BEG_BLOCKTerminalRuleCall_3_5_2_0_q = new TokenAlias(false, true, grammarAccess.getJobAccess().getBEG_BLOCKTerminalRuleCall_3_5_2_0());
		match_Job_END_BLOCKTerminalRuleCall_3_2_2_1_1_3_q = new TokenAlias(false, true, grammarAccess.getJobAccess().getEND_BLOCKTerminalRuleCall_3_2_2_1_1_3());
		match_Job_END_BLOCKTerminalRuleCall_3_4_4_q = new TokenAlias(false, true, grammarAccess.getJobAccess().getEND_BLOCKTerminalRuleCall_3_4_4());
		match_Job_END_BLOCKTerminalRuleCall_3_5_2_2_q = new TokenAlias(false, true, grammarAccess.getJobAccess().getEND_BLOCKTerminalRuleCall_3_5_2_2());
		match_Job_END_BLOCKTerminalRuleCall_4_q = new TokenAlias(false, true, grammarAccess.getJobAccess().getEND_BLOCKTerminalRuleCall_4());
		match_Job___END_BLOCKTerminalRuleCall_3_2_2_1_2_NeedsKeyword_3_2_0_ColonKeyword_3_2_1_BEG_BLOCKTerminalRuleCall_3_2_2_1_0__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getJobAccess().getEND_BLOCKTerminalRuleCall_3_2_2_1_2()), new TokenAlias(false, false, grammarAccess.getJobAccess().getNeedsKeyword_3_2_0()), new TokenAlias(false, false, grammarAccess.getJobAccess().getColonKeyword_3_2_1()), new TokenAlias(false, false, grammarAccess.getJobAccess().getBEG_BLOCKTerminalRuleCall_3_2_2_1_0()));
		match_Job___END_BLOCKTerminalRuleCall_3_4_4_q_StepsKeyword_3_4_0_ColonKeyword_3_4_1_BEG_BLOCKTerminalRuleCall_3_4_2_q__q = new GroupAlias(false, true, new TokenAlias(false, true, grammarAccess.getJobAccess().getEND_BLOCKTerminalRuleCall_3_4_4()), new TokenAlias(false, false, grammarAccess.getJobAccess().getStepsKeyword_3_4_0()), new TokenAlias(false, false, grammarAccess.getJobAccess().getColonKeyword_3_4_1()), new TokenAlias(false, true, grammarAccess.getJobAccess().getBEG_BLOCKTerminalRuleCall_3_4_2()));
		match_Job___END_BLOCKTerminalRuleCall_3_5_2_2_q_PermissionsKeyword_3_5_0_ColonKeyword_3_5_1_BEG_BLOCKTerminalRuleCall_3_5_2_0_q__q = new GroupAlias(false, true, new TokenAlias(false, true, grammarAccess.getJobAccess().getEND_BLOCKTerminalRuleCall_3_5_2_2()), new TokenAlias(false, false, grammarAccess.getJobAccess().getPermissionsKeyword_3_5_0()), new TokenAlias(false, false, grammarAccess.getJobAccess().getColonKeyword_3_5_1()), new TokenAlias(false, true, grammarAccess.getJobAccess().getBEG_BLOCKTerminalRuleCall_3_5_2_0()));
		match_On_BEG_BLOCKTerminalRuleCall_1_q = new TokenAlias(false, true, grammarAccess.getOnAccess().getBEG_BLOCKTerminalRuleCall_1());
		match_On_BEG_BLOCKTerminalRuleCall_2_2_2_0_q = new TokenAlias(false, true, grammarAccess.getOnAccess().getBEG_BLOCKTerminalRuleCall_2_2_2_0());
		match_On_END_BLOCKTerminalRuleCall_2_2_2_2_q = new TokenAlias(false, true, grammarAccess.getOnAccess().getEND_BLOCKTerminalRuleCall_2_2_2_2());
		match_On_END_BLOCKTerminalRuleCall_3_q = new TokenAlias(false, true, grammarAccess.getOnAccess().getEND_BLOCKTerminalRuleCall_3());
		match_On___END_BLOCKTerminalRuleCall_2_2_2_2_q___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__a_ScheduleKeyword_2_2_0_ColonKeyword_2_2_1_BEG_BLOCKTerminalRuleCall_2_2_2_0_q__q = new GroupAlias(false, true, new TokenAlias(false, true, grammarAccess.getOnAccess().getEND_BLOCKTerminalRuleCall_2_2_2_2()), new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getOnAccess().getWorkflow_dispatchKeyword_2_3_0()), new TokenAlias(false, false, grammarAccess.getOnAccess().getColonKeyword_2_3_1())), new TokenAlias(false, false, grammarAccess.getOnAccess().getScheduleKeyword_2_2_0()), new TokenAlias(false, false, grammarAccess.getOnAccess().getColonKeyword_2_2_1()), new TokenAlias(false, true, grammarAccess.getOnAccess().getBEG_BLOCKTerminalRuleCall_2_2_2_0()));
		match_On___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__a = new GroupAlias(true, true, new TokenAlias(false, false, grammarAccess.getOnAccess().getWorkflow_dispatchKeyword_2_3_0()), new TokenAlias(false, false, grammarAccess.getOnAccess().getColonKeyword_2_3_1()));
		match_On___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__p = new GroupAlias(true, false, new TokenAlias(false, false, grammarAccess.getOnAccess().getWorkflow_dispatchKeyword_2_3_0()), new TokenAlias(false, false, grammarAccess.getOnAccess().getColonKeyword_2_3_1()));
		match_Push___END_BLOCKTerminalRuleCall_2_0_2_0_2_BranchesKeyword_2_0_0_ColonKeyword_2_0_1_BEG_BLOCKTerminalRuleCall_2_0_2_0_0__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPushAccess().getEND_BLOCKTerminalRuleCall_2_0_2_0_2()), new TokenAlias(false, false, grammarAccess.getPushAccess().getBranchesKeyword_2_0_0()), new TokenAlias(false, false, grammarAccess.getPushAccess().getColonKeyword_2_0_1()), new TokenAlias(false, false, grammarAccess.getPushAccess().getBEG_BLOCKTerminalRuleCall_2_0_2_0_0()));
		match_Push___END_BLOCKTerminalRuleCall_2_1_2_0_2_TagsKeyword_2_1_0_ColonKeyword_2_1_1_BEG_BLOCKTerminalRuleCall_2_1_2_0_0__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPushAccess().getEND_BLOCKTerminalRuleCall_2_1_2_0_2()), new TokenAlias(false, false, grammarAccess.getPushAccess().getTagsKeyword_2_1_0()), new TokenAlias(false, false, grammarAccess.getPushAccess().getColonKeyword_2_1_1()), new TokenAlias(false, false, grammarAccess.getPushAccess().getBEG_BLOCKTerminalRuleCall_2_1_2_0_0()));
		match_Schedule_BEG_BLOCKTerminalRuleCall_1_q = new TokenAlias(false, true, grammarAccess.getScheduleAccess().getBEG_BLOCKTerminalRuleCall_1());
		match_Schedule_END_BLOCKTerminalRuleCall_5_q = new TokenAlias(false, true, grammarAccess.getScheduleAccess().getEND_BLOCKTerminalRuleCall_5());
		match_Step_BEG_BLOCKTerminalRuleCall_2_q = new TokenAlias(false, true, grammarAccess.getStepAccess().getBEG_BLOCKTerminalRuleCall_2());
		match_Step_BEG_BLOCKTerminalRuleCall_3_6_2_0_q = new TokenAlias(false, true, grammarAccess.getStepAccess().getBEG_BLOCKTerminalRuleCall_3_6_2_0());
		match_Step_BEG_BLOCKTerminalRuleCall_3_7_2_0_q = new TokenAlias(false, true, grammarAccess.getStepAccess().getBEG_BLOCKTerminalRuleCall_3_7_2_0());
		match_Step_END_BLOCKTerminalRuleCall_3_6_2_2_q = new TokenAlias(false, true, grammarAccess.getStepAccess().getEND_BLOCKTerminalRuleCall_3_6_2_2());
		match_Step_END_BLOCKTerminalRuleCall_3_7_2_2_q = new TokenAlias(false, true, grammarAccess.getStepAccess().getEND_BLOCKTerminalRuleCall_3_7_2_2());
		match_Step_END_BLOCKTerminalRuleCall_4_q = new TokenAlias(false, true, grammarAccess.getStepAccess().getEND_BLOCKTerminalRuleCall_4());
		match_Step___END_BLOCKTerminalRuleCall_3_6_2_2_q_WithKeyword_3_6_0_ColonKeyword_3_6_1_BEG_BLOCKTerminalRuleCall_3_6_2_0_q__q = new GroupAlias(false, true, new TokenAlias(false, true, grammarAccess.getStepAccess().getEND_BLOCKTerminalRuleCall_3_6_2_2()), new TokenAlias(false, false, grammarAccess.getStepAccess().getWithKeyword_3_6_0()), new TokenAlias(false, false, grammarAccess.getStepAccess().getColonKeyword_3_6_1()), new TokenAlias(false, true, grammarAccess.getStepAccess().getBEG_BLOCKTerminalRuleCall_3_6_2_0()));
		match_Step___END_BLOCKTerminalRuleCall_3_7_2_2_q_EnvKeyword_3_7_0_ColonKeyword_3_7_1_BEG_BLOCKTerminalRuleCall_3_7_2_0_q__q = new GroupAlias(false, true, new TokenAlias(false, true, grammarAccess.getStepAccess().getEND_BLOCKTerminalRuleCall_3_7_2_2()), new TokenAlias(false, false, grammarAccess.getStepAccess().getEnvKeyword_3_7_0()), new TokenAlias(false, false, grammarAccess.getStepAccess().getColonKeyword_3_7_1()), new TokenAlias(false, true, grammarAccess.getStepAccess().getBEG_BLOCKTerminalRuleCall_3_7_2_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getBEG_BLOCKRule())
			return getBEG_BLOCKToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getEND_BLOCKRule())
			return getEND_BLOCKToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal BEG_BLOCK: 'synthetic:BEGIN';
	 */
	protected String getBEG_BLOCKToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "synthetic:BEGIN";
	}
	
	/**
	 * terminal END_BLOCK: 'synthetic:END';
	 */
	protected String getEND_BLOCKToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "synthetic:END";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Concurrency_BEG_BLOCKTerminalRuleCall_1_q.equals(syntax))
				emit_Concurrency_BEG_BLOCKTerminalRuleCall_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Concurrency_END_BLOCKTerminalRuleCall_3_q.equals(syntax))
				emit_Concurrency_END_BLOCKTerminalRuleCall_3_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Environment_BEG_BLOCKTerminalRuleCall_1_q.equals(syntax))
				emit_Environment_BEG_BLOCKTerminalRuleCall_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Environment_END_BLOCKTerminalRuleCall_3_q.equals(syntax))
				emit_Environment_END_BLOCKTerminalRuleCall_3_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_GithubActions_BEG_BLOCKTerminalRuleCall_3_2_q.equals(syntax))
				emit_GithubActions_BEG_BLOCKTerminalRuleCall_3_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_GithubActions_BEG_BLOCKTerminalRuleCall_4_2_0_q.equals(syntax))
				emit_GithubActions_BEG_BLOCKTerminalRuleCall_4_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_GithubActions_BEG_BLOCKTerminalRuleCall_5_2_0_q.equals(syntax))
				emit_GithubActions_BEG_BLOCKTerminalRuleCall_5_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_GithubActions_END_BLOCKTerminalRuleCall_3_4_q.equals(syntax))
				emit_GithubActions_END_BLOCKTerminalRuleCall_3_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_GithubActions_END_BLOCKTerminalRuleCall_4_2_2_q.equals(syntax))
				emit_GithubActions_END_BLOCKTerminalRuleCall_4_2_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_GithubActions_END_BLOCKTerminalRuleCall_5_2_2_q.equals(syntax))
				emit_GithubActions_END_BLOCKTerminalRuleCall_5_2_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_GithubActions___END_BLOCKTerminalRuleCall_3_4_q_JobsKeyword_3_0_ColonKeyword_3_1_BEG_BLOCKTerminalRuleCall_3_2_q__q.equals(syntax))
				emit_GithubActions___END_BLOCKTerminalRuleCall_3_4_q_JobsKeyword_3_0_ColonKeyword_3_1_BEG_BLOCKTerminalRuleCall_3_2_q__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_GithubActions___END_BLOCKTerminalRuleCall_4_2_2_q_PermissionsKeyword_4_0_ColonKeyword_4_1_BEG_BLOCKTerminalRuleCall_4_2_0_q__q.equals(syntax))
				emit_GithubActions___END_BLOCKTerminalRuleCall_4_2_2_q_PermissionsKeyword_4_0_ColonKeyword_4_1_BEG_BLOCKTerminalRuleCall_4_2_0_q__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_GithubActions___END_BLOCKTerminalRuleCall_5_2_2_q_EnvKeyword_5_0_ColonKeyword_5_1_BEG_BLOCKTerminalRuleCall_5_2_0_q__q.equals(syntax))
				emit_GithubActions___END_BLOCKTerminalRuleCall_5_2_2_q_EnvKeyword_5_0_ColonKeyword_5_1_BEG_BLOCKTerminalRuleCall_5_2_0_q__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Job_BEG_BLOCKTerminalRuleCall_2_q.equals(syntax))
				emit_Job_BEG_BLOCKTerminalRuleCall_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Job_BEG_BLOCKTerminalRuleCall_3_2_2_1_1_1_q.equals(syntax))
				emit_Job_BEG_BLOCKTerminalRuleCall_3_2_2_1_1_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Job_BEG_BLOCKTerminalRuleCall_3_4_2_q.equals(syntax))
				emit_Job_BEG_BLOCKTerminalRuleCall_3_4_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Job_BEG_BLOCKTerminalRuleCall_3_5_2_0_q.equals(syntax))
				emit_Job_BEG_BLOCKTerminalRuleCall_3_5_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Job_END_BLOCKTerminalRuleCall_3_2_2_1_1_3_q.equals(syntax))
				emit_Job_END_BLOCKTerminalRuleCall_3_2_2_1_1_3_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Job_END_BLOCKTerminalRuleCall_3_4_4_q.equals(syntax))
				emit_Job_END_BLOCKTerminalRuleCall_3_4_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Job_END_BLOCKTerminalRuleCall_3_5_2_2_q.equals(syntax))
				emit_Job_END_BLOCKTerminalRuleCall_3_5_2_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Job_END_BLOCKTerminalRuleCall_4_q.equals(syntax))
				emit_Job_END_BLOCKTerminalRuleCall_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Job___END_BLOCKTerminalRuleCall_3_2_2_1_2_NeedsKeyword_3_2_0_ColonKeyword_3_2_1_BEG_BLOCKTerminalRuleCall_3_2_2_1_0__q.equals(syntax))
				emit_Job___END_BLOCKTerminalRuleCall_3_2_2_1_2_NeedsKeyword_3_2_0_ColonKeyword_3_2_1_BEG_BLOCKTerminalRuleCall_3_2_2_1_0__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Job___END_BLOCKTerminalRuleCall_3_4_4_q_StepsKeyword_3_4_0_ColonKeyword_3_4_1_BEG_BLOCKTerminalRuleCall_3_4_2_q__q.equals(syntax))
				emit_Job___END_BLOCKTerminalRuleCall_3_4_4_q_StepsKeyword_3_4_0_ColonKeyword_3_4_1_BEG_BLOCKTerminalRuleCall_3_4_2_q__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Job___END_BLOCKTerminalRuleCall_3_5_2_2_q_PermissionsKeyword_3_5_0_ColonKeyword_3_5_1_BEG_BLOCKTerminalRuleCall_3_5_2_0_q__q.equals(syntax))
				emit_Job___END_BLOCKTerminalRuleCall_3_5_2_2_q_PermissionsKeyword_3_5_0_ColonKeyword_3_5_1_BEG_BLOCKTerminalRuleCall_3_5_2_0_q__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_On_BEG_BLOCKTerminalRuleCall_1_q.equals(syntax))
				emit_On_BEG_BLOCKTerminalRuleCall_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_On_BEG_BLOCKTerminalRuleCall_2_2_2_0_q.equals(syntax))
				emit_On_BEG_BLOCKTerminalRuleCall_2_2_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_On_END_BLOCKTerminalRuleCall_2_2_2_2_q.equals(syntax))
				emit_On_END_BLOCKTerminalRuleCall_2_2_2_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_On_END_BLOCKTerminalRuleCall_3_q.equals(syntax))
				emit_On_END_BLOCKTerminalRuleCall_3_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_On___END_BLOCKTerminalRuleCall_2_2_2_2_q___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__a_ScheduleKeyword_2_2_0_ColonKeyword_2_2_1_BEG_BLOCKTerminalRuleCall_2_2_2_0_q__q.equals(syntax))
				emit_On___END_BLOCKTerminalRuleCall_2_2_2_2_q___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__a_ScheduleKeyword_2_2_0_ColonKeyword_2_2_1_BEG_BLOCKTerminalRuleCall_2_2_2_0_q__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_On___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__a.equals(syntax))
				emit_On___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_On___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__p.equals(syntax))
				emit_On___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Push___END_BLOCKTerminalRuleCall_2_0_2_0_2_BranchesKeyword_2_0_0_ColonKeyword_2_0_1_BEG_BLOCKTerminalRuleCall_2_0_2_0_0__q.equals(syntax))
				emit_Push___END_BLOCKTerminalRuleCall_2_0_2_0_2_BranchesKeyword_2_0_0_ColonKeyword_2_0_1_BEG_BLOCKTerminalRuleCall_2_0_2_0_0__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Push___END_BLOCKTerminalRuleCall_2_1_2_0_2_TagsKeyword_2_1_0_ColonKeyword_2_1_1_BEG_BLOCKTerminalRuleCall_2_1_2_0_0__q.equals(syntax))
				emit_Push___END_BLOCKTerminalRuleCall_2_1_2_0_2_TagsKeyword_2_1_0_ColonKeyword_2_1_1_BEG_BLOCKTerminalRuleCall_2_1_2_0_0__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Schedule_BEG_BLOCKTerminalRuleCall_1_q.equals(syntax))
				emit_Schedule_BEG_BLOCKTerminalRuleCall_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Schedule_END_BLOCKTerminalRuleCall_5_q.equals(syntax))
				emit_Schedule_END_BLOCKTerminalRuleCall_5_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Step_BEG_BLOCKTerminalRuleCall_2_q.equals(syntax))
				emit_Step_BEG_BLOCKTerminalRuleCall_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Step_BEG_BLOCKTerminalRuleCall_3_6_2_0_q.equals(syntax))
				emit_Step_BEG_BLOCKTerminalRuleCall_3_6_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Step_BEG_BLOCKTerminalRuleCall_3_7_2_0_q.equals(syntax))
				emit_Step_BEG_BLOCKTerminalRuleCall_3_7_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Step_END_BLOCKTerminalRuleCall_3_6_2_2_q.equals(syntax))
				emit_Step_END_BLOCKTerminalRuleCall_3_6_2_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Step_END_BLOCKTerminalRuleCall_3_7_2_2_q.equals(syntax))
				emit_Step_END_BLOCKTerminalRuleCall_3_7_2_2_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Step_END_BLOCKTerminalRuleCall_4_q.equals(syntax))
				emit_Step_END_BLOCKTerminalRuleCall_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Step___END_BLOCKTerminalRuleCall_3_6_2_2_q_WithKeyword_3_6_0_ColonKeyword_3_6_1_BEG_BLOCKTerminalRuleCall_3_6_2_0_q__q.equals(syntax))
				emit_Step___END_BLOCKTerminalRuleCall_3_6_2_2_q_WithKeyword_3_6_0_ColonKeyword_3_6_1_BEG_BLOCKTerminalRuleCall_3_6_2_0_q__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Step___END_BLOCKTerminalRuleCall_3_7_2_2_q_EnvKeyword_3_7_0_ColonKeyword_3_7_1_BEG_BLOCKTerminalRuleCall_3_7_2_0_q__q.equals(syntax))
				emit_Step___END_BLOCKTerminalRuleCall_3_7_2_2_q_EnvKeyword_3_7_0_ColonKeyword_3_7_1_BEG_BLOCKTerminalRuleCall_3_7_2_0_q__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'cancel-in-progress' ':' cancelInProgress=EBoolean
	 *     (rule start) (ambiguity) 'group' ':' group=EString
	 *     (rule start) (ambiguity) END_BLOCK? (rule start)
	 
	 * </pre>
	 */
	protected void emit_Concurrency_BEG_BLOCKTerminalRuleCall_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) BEG_BLOCK? (ambiguity) (rule start)
	 *     cancelInProgress=EBoolean (ambiguity) (rule end)
	 *     group=EString (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_Concurrency_END_BLOCKTerminalRuleCall_3_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'name' ':' name=EString
	 *     (rule start) (ambiguity) 'url' ':' url=EString
	 *     (rule start) (ambiguity) END_BLOCK? (rule start)
	 
	 * </pre>
	 */
	protected void emit_Environment_BEG_BLOCKTerminalRuleCall_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) BEG_BLOCK? (ambiguity) (rule start)
	 *     name=EString (ambiguity) (rule end)
	 *     url=EString (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_Environment_END_BLOCKTerminalRuleCall_3_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'jobs' ':' (ambiguity) jobs+=Job
	 *     concurrency=Concurrency 'jobs' ':' (ambiguity) jobs+=Job
	 *     env+=KeyValuePair END_BLOCK? 'jobs' ':' (ambiguity) jobs+=Job
	 *     name=EString 'jobs' ':' (ambiguity) jobs+=Job
	 *     on=On 'jobs' ':' (ambiguity) jobs+=Job
	 *     permissions+=KeyValuePair END_BLOCK? 'jobs' ':' (ambiguity) jobs+=Job
	 
	 * </pre>
	 */
	protected void emit_GithubActions_BEG_BLOCKTerminalRuleCall_3_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 *     concurrency=Concurrency 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 *     env+=KeyValuePair END_BLOCK? 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 *     jobs+=Job END_BLOCK? 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 *     name=EString 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 *     on=On 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 
	 * </pre>
	 */
	protected void emit_GithubActions_BEG_BLOCKTerminalRuleCall_4_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'env' ':' (ambiguity) env+=KeyValuePair
	 *     concurrency=Concurrency 'env' ':' (ambiguity) env+=KeyValuePair
	 *     jobs+=Job END_BLOCK? 'env' ':' (ambiguity) env+=KeyValuePair
	 *     name=EString 'env' ':' (ambiguity) env+=KeyValuePair
	 *     on=On 'env' ':' (ambiguity) env+=KeyValuePair
	 *     permissions+=KeyValuePair END_BLOCK? 'env' ':' (ambiguity) env+=KeyValuePair
	 
	 * </pre>
	 */
	protected void emit_GithubActions_BEG_BLOCKTerminalRuleCall_5_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     jobs+=Job (ambiguity) 'concurrency' ':' concurrency=Concurrency
	 *     jobs+=Job (ambiguity) 'env' ':' BEG_BLOCK? env+=KeyValuePair
	 *     jobs+=Job (ambiguity) 'name' ':' name=EString
	 *     jobs+=Job (ambiguity) 'on' ':' on=On
	 *     jobs+=Job (ambiguity) 'permissions' ':' BEG_BLOCK? permissions+=KeyValuePair
	 *     jobs+=Job (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_GithubActions_END_BLOCKTerminalRuleCall_3_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     permissions+=KeyValuePair (ambiguity) 'concurrency' ':' concurrency=Concurrency
	 *     permissions+=KeyValuePair (ambiguity) 'env' ':' BEG_BLOCK? env+=KeyValuePair
	 *     permissions+=KeyValuePair (ambiguity) 'jobs' ':' BEG_BLOCK? jobs+=Job
	 *     permissions+=KeyValuePair (ambiguity) 'name' ':' name=EString
	 *     permissions+=KeyValuePair (ambiguity) 'on' ':' on=On
	 *     permissions+=KeyValuePair (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_GithubActions_END_BLOCKTerminalRuleCall_4_2_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     env+=KeyValuePair (ambiguity) 'concurrency' ':' concurrency=Concurrency
	 *     env+=KeyValuePair (ambiguity) 'jobs' ':' BEG_BLOCK? jobs+=Job
	 *     env+=KeyValuePair (ambiguity) 'name' ':' name=EString
	 *     env+=KeyValuePair (ambiguity) 'on' ':' on=On
	 *     env+=KeyValuePair (ambiguity) 'permissions' ':' BEG_BLOCK? permissions+=KeyValuePair
	 *     env+=KeyValuePair (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_GithubActions_END_BLOCKTerminalRuleCall_5_2_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK? 'jobs' ':' BEG_BLOCK?)?
	 *
	 * This ambiguous syntax occurs at:
	 *     jobs+=Job (ambiguity) jobs+=Job
	 
	 * </pre>
	 */
	protected void emit_GithubActions___END_BLOCKTerminalRuleCall_3_4_q_JobsKeyword_3_0_ColonKeyword_3_1_BEG_BLOCKTerminalRuleCall_3_2_q__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK? 'permissions' ':' BEG_BLOCK?)?
	 *
	 * This ambiguous syntax occurs at:
	 *     permissions+=KeyValuePair (ambiguity) permissions+=KeyValuePair
	 
	 * </pre>
	 */
	protected void emit_GithubActions___END_BLOCKTerminalRuleCall_4_2_2_q_PermissionsKeyword_4_0_ColonKeyword_4_1_BEG_BLOCKTerminalRuleCall_4_2_0_q__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK? 'env' ':' BEG_BLOCK?)?
	 *
	 * This ambiguous syntax occurs at:
	 *     env+=KeyValuePair (ambiguity) env+=KeyValuePair
	 
	 * </pre>
	 */
	protected void emit_GithubActions___END_BLOCKTerminalRuleCall_5_2_2_q_EnvKeyword_5_0_ColonKeyword_5_1_BEG_BLOCKTerminalRuleCall_5_2_0_q__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     id=EString ':' (ambiguity) 'environment' ':' environment=Environment
	 *     id=EString ':' (ambiguity) 'name' ':' name=EString
	 *     id=EString ':' (ambiguity) 'needs' ':' '[' needs+=EString
	 *     id=EString ':' (ambiguity) 'needs' ':' BEG_BLOCK '-' BEG_BLOCK? needs+=EString
	 *     id=EString ':' (ambiguity) 'needs' ':' needs+=EString
	 *     id=EString ':' (ambiguity) 'permissions' ':' BEG_BLOCK? permissions+=KeyValuePair
	 *     id=EString ':' (ambiguity) 'runs-on' ':' runsOn=EString
	 *     id=EString ':' (ambiguity) 'steps' ':' BEG_BLOCK? steps+=Step
	 *     id=EString ':' (ambiguity) END_BLOCK? (rule end)
	 
	 * </pre>
	 */
	protected void emit_Job_BEG_BLOCKTerminalRuleCall_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     environment=Environment 'needs' ':' BEG_BLOCK '-' (ambiguity) needs+=EString
	 *     id=EString ':' BEG_BLOCK? 'needs' ':' BEG_BLOCK '-' (ambiguity) needs+=EString
	 *     name=EString 'needs' ':' BEG_BLOCK '-' (ambiguity) needs+=EString
	 *     needs+=EString ']' 'needs' ':' BEG_BLOCK '-' (ambiguity) needs+=EString
	 *     needs+=EString 'needs' ':' BEG_BLOCK '-' (ambiguity) needs+=EString
	 *     needs+=EString END_BLOCK? (END_BLOCK 'needs' ':' BEG_BLOCK)? '-' (ambiguity) needs+=EString
	 *     permissions+=KeyValuePair END_BLOCK? 'needs' ':' BEG_BLOCK '-' (ambiguity) needs+=EString
	 *     runsOn=EString 'needs' ':' BEG_BLOCK '-' (ambiguity) needs+=EString
	 *     steps+=Step END_BLOCK? 'needs' ':' BEG_BLOCK '-' (ambiguity) needs+=EString
	 
	 * </pre>
	 */
	protected void emit_Job_BEG_BLOCKTerminalRuleCall_3_2_2_1_1_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     environment=Environment 'steps' ':' (ambiguity) steps+=Step
	 *     id=EString ':' BEG_BLOCK? 'steps' ':' (ambiguity) steps+=Step
	 *     name=EString 'steps' ':' (ambiguity) steps+=Step
	 *     needs+=EString ']' 'steps' ':' (ambiguity) steps+=Step
	 *     needs+=EString 'steps' ':' (ambiguity) steps+=Step
	 *     needs+=EString END_BLOCK? END_BLOCK 'steps' ':' (ambiguity) steps+=Step
	 *     permissions+=KeyValuePair END_BLOCK? 'steps' ':' (ambiguity) steps+=Step
	 *     runsOn=EString 'steps' ':' (ambiguity) steps+=Step
	 
	 * </pre>
	 */
	protected void emit_Job_BEG_BLOCKTerminalRuleCall_3_4_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     environment=Environment 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 *     id=EString ':' BEG_BLOCK? 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 *     name=EString 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 *     needs+=EString ']' 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 *     needs+=EString 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 *     needs+=EString END_BLOCK? END_BLOCK 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 *     runsOn=EString 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 *     steps+=Step END_BLOCK? 'permissions' ':' (ambiguity) permissions+=KeyValuePair
	 
	 * </pre>
	 */
	protected void emit_Job_BEG_BLOCKTerminalRuleCall_3_5_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     needs+=EString (ambiguity) (END_BLOCK 'needs' ':' BEG_BLOCK)? '-' BEG_BLOCK? needs+=EString
	 *     needs+=EString (ambiguity) END_BLOCK 'environment' ':' environment=Environment
	 *     needs+=EString (ambiguity) END_BLOCK 'name' ':' name=EString
	 *     needs+=EString (ambiguity) END_BLOCK 'needs' ':' '[' needs+=EString
	 *     needs+=EString (ambiguity) END_BLOCK 'needs' ':' needs+=EString
	 *     needs+=EString (ambiguity) END_BLOCK 'permissions' ':' BEG_BLOCK? permissions+=KeyValuePair
	 *     needs+=EString (ambiguity) END_BLOCK 'runs-on' ':' runsOn=EString
	 *     needs+=EString (ambiguity) END_BLOCK 'steps' ':' BEG_BLOCK? steps+=Step
	 *     needs+=EString (ambiguity) END_BLOCK END_BLOCK? (rule end)
	 
	 * </pre>
	 */
	protected void emit_Job_END_BLOCKTerminalRuleCall_3_2_2_1_1_3_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     steps+=Step (ambiguity) 'environment' ':' environment=Environment
	 *     steps+=Step (ambiguity) 'name' ':' name=EString
	 *     steps+=Step (ambiguity) 'needs' ':' '[' needs+=EString
	 *     steps+=Step (ambiguity) 'needs' ':' BEG_BLOCK '-' BEG_BLOCK? needs+=EString
	 *     steps+=Step (ambiguity) 'needs' ':' needs+=EString
	 *     steps+=Step (ambiguity) 'permissions' ':' BEG_BLOCK? permissions+=KeyValuePair
	 *     steps+=Step (ambiguity) 'runs-on' ':' runsOn=EString
	 *     steps+=Step (ambiguity) END_BLOCK? (rule end)
	 
	 * </pre>
	 */
	protected void emit_Job_END_BLOCKTerminalRuleCall_3_4_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     permissions+=KeyValuePair (ambiguity) 'environment' ':' environment=Environment
	 *     permissions+=KeyValuePair (ambiguity) 'name' ':' name=EString
	 *     permissions+=KeyValuePair (ambiguity) 'needs' ':' '[' needs+=EString
	 *     permissions+=KeyValuePair (ambiguity) 'needs' ':' BEG_BLOCK '-' BEG_BLOCK? needs+=EString
	 *     permissions+=KeyValuePair (ambiguity) 'needs' ':' needs+=EString
	 *     permissions+=KeyValuePair (ambiguity) 'runs-on' ':' runsOn=EString
	 *     permissions+=KeyValuePair (ambiguity) 'steps' ':' BEG_BLOCK? steps+=Step
	 *     permissions+=KeyValuePair (ambiguity) END_BLOCK? (rule end)
	 
	 * </pre>
	 */
	protected void emit_Job_END_BLOCKTerminalRuleCall_3_5_2_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     environment=Environment (ambiguity) (rule end)
	 *     id=EString ':' BEG_BLOCK? (ambiguity) (rule end)
	 *     name=EString (ambiguity) (rule end)
	 *     needs+=EString ']' (ambiguity) (rule end)
	 *     needs+=EString (ambiguity) (rule end)
	 *     needs+=EString END_BLOCK? END_BLOCK (ambiguity) (rule end)
	 *     permissions+=KeyValuePair END_BLOCK? (ambiguity) (rule end)
	 *     runsOn=EString (ambiguity) (rule end)
	 *     steps+=Step END_BLOCK? (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_Job_END_BLOCKTerminalRuleCall_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK 'needs' ':' BEG_BLOCK)?
	 *
	 * This ambiguous syntax occurs at:
	 *     needs+=EString END_BLOCK? (ambiguity) '-' BEG_BLOCK? needs+=EString
	 
	 * </pre>
	 */
	protected void emit_Job___END_BLOCKTerminalRuleCall_3_2_2_1_2_NeedsKeyword_3_2_0_ColonKeyword_3_2_1_BEG_BLOCKTerminalRuleCall_3_2_2_1_0__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK? 'steps' ':' BEG_BLOCK?)?
	 *
	 * This ambiguous syntax occurs at:
	 *     steps+=Step (ambiguity) steps+=Step
	 
	 * </pre>
	 */
	protected void emit_Job___END_BLOCKTerminalRuleCall_3_4_4_q_StepsKeyword_3_4_0_ColonKeyword_3_4_1_BEG_BLOCKTerminalRuleCall_3_4_2_q__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK? 'permissions' ':' BEG_BLOCK?)?
	 *
	 * This ambiguous syntax occurs at:
	 *     permissions+=KeyValuePair (ambiguity) permissions+=KeyValuePair
	 
	 * </pre>
	 */
	protected void emit_Job___END_BLOCKTerminalRuleCall_3_5_2_2_q_PermissionsKeyword_3_5_0_ColonKeyword_3_5_1_BEG_BLOCKTerminalRuleCall_3_5_2_0_q__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) ('workflow_dispatch' ':')* 'pull_request' ':' pullRequest=Pull_request
	 *     (rule start) (ambiguity) ('workflow_dispatch' ':')* 'push' ':' push=Push
	 *     (rule start) (ambiguity) ('workflow_dispatch' ':')* 'schedule' ':' BEG_BLOCK? schedule+=Schedule
	 *     (rule start) (ambiguity) ('workflow_dispatch' ':')* END_BLOCK? (rule start)
	 *     (rule start) (ambiguity) ('workflow_dispatch' ':')+ workflowDispatch=EString
	 
	 * </pre>
	 */
	protected void emit_On_BEG_BLOCKTerminalRuleCall_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) BEG_BLOCK? ('workflow_dispatch' ':')* 'schedule' ':' (ambiguity) schedule+=Schedule
	 *     pullRequest=Pull_request ('workflow_dispatch' ':')* 'schedule' ':' (ambiguity) schedule+=Schedule
	 *     push=Push ('workflow_dispatch' ':')* 'schedule' ':' (ambiguity) schedule+=Schedule
	 *     workflowDispatch=EString ('workflow_dispatch' ':')* 'schedule' ':' (ambiguity) schedule+=Schedule
	 
	 * </pre>
	 */
	protected void emit_On_BEG_BLOCKTerminalRuleCall_2_2_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     schedule+=Schedule (ambiguity) ('workflow_dispatch' ':')* 'pull_request' ':' pullRequest=Pull_request
	 *     schedule+=Schedule (ambiguity) ('workflow_dispatch' ':')* 'push' ':' push=Push
	 *     schedule+=Schedule (ambiguity) ('workflow_dispatch' ':')* END_BLOCK? (rule end)
	 *     schedule+=Schedule (ambiguity) ('workflow_dispatch' ':')+ workflowDispatch=EString
	 
	 * </pre>
	 */
	protected void emit_On_END_BLOCKTerminalRuleCall_2_2_2_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) BEG_BLOCK? ('workflow_dispatch' ':')* (ambiguity) (rule start)
	 *     pullRequest=Pull_request ('workflow_dispatch' ':')* (ambiguity) (rule end)
	 *     push=Push ('workflow_dispatch' ':')* (ambiguity) (rule end)
	 *     schedule+=Schedule END_BLOCK? ('workflow_dispatch' ':')* (ambiguity) (rule end)
	 *     workflowDispatch=EString ('workflow_dispatch' ':')* (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_On_END_BLOCKTerminalRuleCall_3_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK? ('workflow_dispatch' ':')* 'schedule' ':' BEG_BLOCK?)?
	 *
	 * This ambiguous syntax occurs at:
	 *     schedule+=Schedule (ambiguity) schedule+=Schedule
	 
	 * </pre>
	 */
	protected void emit_On___END_BLOCKTerminalRuleCall_2_2_2_2_q___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__a_ScheduleKeyword_2_2_0_ColonKeyword_2_2_1_BEG_BLOCKTerminalRuleCall_2_2_2_0_q__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('workflow_dispatch' ':')*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) BEG_BLOCK? (ambiguity) 'pull_request' ':' pullRequest=Pull_request
	 *     (rule start) BEG_BLOCK? (ambiguity) 'push' ':' push=Push
	 *     (rule start) BEG_BLOCK? (ambiguity) 'schedule' ':' BEG_BLOCK? schedule+=Schedule
	 *     (rule start) BEG_BLOCK? (ambiguity) END_BLOCK? (rule start)
	 *     pullRequest=Pull_request (ambiguity) 'pull_request' ':' pullRequest=Pull_request
	 *     pullRequest=Pull_request (ambiguity) 'push' ':' push=Push
	 *     pullRequest=Pull_request (ambiguity) 'schedule' ':' BEG_BLOCK? schedule+=Schedule
	 *     pullRequest=Pull_request (ambiguity) END_BLOCK? (rule end)
	 *     push=Push (ambiguity) 'pull_request' ':' pullRequest=Pull_request
	 *     push=Push (ambiguity) 'push' ':' push=Push
	 *     push=Push (ambiguity) 'schedule' ':' BEG_BLOCK? schedule+=Schedule
	 *     push=Push (ambiguity) END_BLOCK? (rule end)
	 *     schedule+=Schedule END_BLOCK? (ambiguity) 'pull_request' ':' pullRequest=Pull_request
	 *     schedule+=Schedule END_BLOCK? (ambiguity) 'push' ':' push=Push
	 *     schedule+=Schedule END_BLOCK? (ambiguity) END_BLOCK? (rule end)
	 *     workflowDispatch=EString (ambiguity) 'pull_request' ':' pullRequest=Pull_request
	 *     workflowDispatch=EString (ambiguity) 'push' ':' push=Push
	 *     workflowDispatch=EString (ambiguity) 'schedule' ':' BEG_BLOCK? schedule+=Schedule
	 *     workflowDispatch=EString (ambiguity) END_BLOCK? (rule end)
	 
	 * </pre>
	 */
	protected void emit_On___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     ('workflow_dispatch' ':')+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) BEG_BLOCK? (ambiguity) workflowDispatch=EString
	 *     pullRequest=Pull_request (ambiguity) workflowDispatch=EString
	 *     push=Push (ambiguity) workflowDispatch=EString
	 *     schedule+=Schedule END_BLOCK? (ambiguity) workflowDispatch=EString
	 *     workflowDispatch=EString (ambiguity) workflowDispatch=EString
	 
	 * </pre>
	 */
	protected void emit_On___Workflow_dispatchKeyword_2_3_0_ColonKeyword_2_3_1__p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK 'branches' ':' BEG_BLOCK)?
	 *
	 * This ambiguous syntax occurs at:
	 *     branches+=EString END_BLOCK (ambiguity) '-' BEG_BLOCK branches+=EString
	 
	 * </pre>
	 */
	protected void emit_Push___END_BLOCKTerminalRuleCall_2_0_2_0_2_BranchesKeyword_2_0_0_ColonKeyword_2_0_1_BEG_BLOCKTerminalRuleCall_2_0_2_0_0__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK 'tags' ':' BEG_BLOCK)?
	 *
	 * This ambiguous syntax occurs at:
	 *     tags+=EString END_BLOCK (ambiguity) '-' BEG_BLOCK tags+=EString
	 
	 * </pre>
	 */
	protected void emit_Push___END_BLOCKTerminalRuleCall_2_1_2_0_2_TagsKeyword_2_1_0_ColonKeyword_2_1_1_BEG_BLOCKTerminalRuleCall_2_1_2_0_0__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '-' (ambiguity) 'cron' ':' cron=EString
	 
	 * </pre>
	 */
	protected void emit_Schedule_BEG_BLOCKTerminalRuleCall_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     cron=EString (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_Schedule_END_BLOCKTerminalRuleCall_5_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '-' (ambiguity) 'env' ':' BEG_BLOCK? env+=KeyValuePair
	 *     (rule start) '-' (ambiguity) 'id' ':' id=EString
	 *     (rule start) '-' (ambiguity) 'if' ':' if=EString
	 *     (rule start) '-' (ambiguity) 'name' ':' name=EString
	 *     (rule start) '-' (ambiguity) 'run' ':' run=EString
	 *     (rule start) '-' (ambiguity) 'uses' ':' uses=EString
	 *     (rule start) '-' (ambiguity) 'with' ':' BEG_BLOCK? with+=KeyValuePair
	 *     (rule start) '-' (ambiguity) 'working-directory' ':' workingDirectory=EString
	 *     (rule start) '-' (ambiguity) END_BLOCK? (rule start)
	 
	 * </pre>
	 */
	protected void emit_Step_BEG_BLOCKTerminalRuleCall_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '-' BEG_BLOCK? 'with' ':' (ambiguity) with+=KeyValuePair
	 *     env+=KeyValuePair END_BLOCK? 'with' ':' (ambiguity) with+=KeyValuePair
	 *     id=EString 'with' ':' (ambiguity) with+=KeyValuePair
	 *     if=EString 'with' ':' (ambiguity) with+=KeyValuePair
	 *     name=EString 'with' ':' (ambiguity) with+=KeyValuePair
	 *     run=EString 'with' ':' (ambiguity) with+=KeyValuePair
	 *     uses=EString 'with' ':' (ambiguity) with+=KeyValuePair
	 *     workingDirectory=EString 'with' ':' (ambiguity) with+=KeyValuePair
	 
	 * </pre>
	 */
	protected void emit_Step_BEG_BLOCKTerminalRuleCall_3_6_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     BEG_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '-' BEG_BLOCK? 'env' ':' (ambiguity) env+=KeyValuePair
	 *     id=EString 'env' ':' (ambiguity) env+=KeyValuePair
	 *     if=EString 'env' ':' (ambiguity) env+=KeyValuePair
	 *     name=EString 'env' ':' (ambiguity) env+=KeyValuePair
	 *     run=EString 'env' ':' (ambiguity) env+=KeyValuePair
	 *     uses=EString 'env' ':' (ambiguity) env+=KeyValuePair
	 *     with+=KeyValuePair END_BLOCK? 'env' ':' (ambiguity) env+=KeyValuePair
	 *     workingDirectory=EString 'env' ':' (ambiguity) env+=KeyValuePair
	 
	 * </pre>
	 */
	protected void emit_Step_BEG_BLOCKTerminalRuleCall_3_7_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     with+=KeyValuePair (ambiguity) 'env' ':' BEG_BLOCK? env+=KeyValuePair
	 *     with+=KeyValuePair (ambiguity) 'id' ':' id=EString
	 *     with+=KeyValuePair (ambiguity) 'if' ':' if=EString
	 *     with+=KeyValuePair (ambiguity) 'name' ':' name=EString
	 *     with+=KeyValuePair (ambiguity) 'run' ':' run=EString
	 *     with+=KeyValuePair (ambiguity) 'uses' ':' uses=EString
	 *     with+=KeyValuePair (ambiguity) 'working-directory' ':' workingDirectory=EString
	 *     with+=KeyValuePair (ambiguity) END_BLOCK? (rule end)
	 
	 * </pre>
	 */
	protected void emit_Step_END_BLOCKTerminalRuleCall_3_6_2_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     env+=KeyValuePair (ambiguity) 'id' ':' id=EString
	 *     env+=KeyValuePair (ambiguity) 'if' ':' if=EString
	 *     env+=KeyValuePair (ambiguity) 'name' ':' name=EString
	 *     env+=KeyValuePair (ambiguity) 'run' ':' run=EString
	 *     env+=KeyValuePair (ambiguity) 'uses' ':' uses=EString
	 *     env+=KeyValuePair (ambiguity) 'with' ':' BEG_BLOCK? with+=KeyValuePair
	 *     env+=KeyValuePair (ambiguity) 'working-directory' ':' workingDirectory=EString
	 *     env+=KeyValuePair (ambiguity) END_BLOCK? (rule end)
	 
	 * </pre>
	 */
	protected void emit_Step_END_BLOCKTerminalRuleCall_3_7_2_2_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     END_BLOCK?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) '-' BEG_BLOCK? (ambiguity) (rule start)
	 *     env+=KeyValuePair END_BLOCK? (ambiguity) (rule end)
	 *     id=EString (ambiguity) (rule end)
	 *     if=EString (ambiguity) (rule end)
	 *     name=EString (ambiguity) (rule end)
	 *     run=EString (ambiguity) (rule end)
	 *     uses=EString (ambiguity) (rule end)
	 *     with+=KeyValuePair END_BLOCK? (ambiguity) (rule end)
	 *     workingDirectory=EString (ambiguity) (rule end)
	 
	 * </pre>
	 */
	protected void emit_Step_END_BLOCKTerminalRuleCall_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK? 'with' ':' BEG_BLOCK?)?
	 *
	 * This ambiguous syntax occurs at:
	 *     with+=KeyValuePair (ambiguity) with+=KeyValuePair
	 
	 * </pre>
	 */
	protected void emit_Step___END_BLOCKTerminalRuleCall_3_6_2_2_q_WithKeyword_3_6_0_ColonKeyword_3_6_1_BEG_BLOCKTerminalRuleCall_3_6_2_0_q__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK? 'env' ':' BEG_BLOCK?)?
	 *
	 * This ambiguous syntax occurs at:
	 *     env+=KeyValuePair (ambiguity) env+=KeyValuePair
	 
	 * </pre>
	 */
	protected void emit_Step___END_BLOCKTerminalRuleCall_3_7_2_2_q_EnvKeyword_3_7_0_ColonKeyword_3_7_1_BEG_BLOCKTerminalRuleCall_3_7_2_0_q__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
