/*
 * generated by Xtext 2.42.0
 */
package pt.isep.yamldslgen.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import pt.isep.yamldslgen.xtext.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MyDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_GithubActions___END_BLOCKTerminalRuleCall_2_4_JobsKeyword_2_0_ColonKeyword_2_1_BEG_BLOCKTerminalRuleCall_2_2__q;
	protected AbstractElementAlias match_Job___END_BLOCKTerminalRuleCall_3_1_2_0_2_NeedsKeyword_3_1_0_ColonKeyword_3_1_1_BEG_BLOCKTerminalRuleCall_3_1_2_0_0__q;
	protected AbstractElementAlias match_Job___END_BLOCKTerminalRuleCall_3_2_4_StepsKeyword_3_2_0_ColonKeyword_3_2_1_BEG_BLOCKTerminalRuleCall_3_2_2__q;
	protected AbstractElementAlias match_Push___END_BLOCKTerminalRuleCall_2_0_2_0_2_BranchesKeyword_2_0_0_ColonKeyword_2_0_1_BEG_BLOCKTerminalRuleCall_2_0_2_0_0__q;
	protected AbstractElementAlias match_Push___END_BLOCKTerminalRuleCall_2_1_2_0_2_TagsKeyword_2_1_0_ColonKeyword_2_1_1_BEG_BLOCKTerminalRuleCall_2_1_2_0_0__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MyDslGrammarAccess) access;
		match_GithubActions___END_BLOCKTerminalRuleCall_2_4_JobsKeyword_2_0_ColonKeyword_2_1_BEG_BLOCKTerminalRuleCall_2_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getGithubActionsAccess().getEND_BLOCKTerminalRuleCall_2_4()), new TokenAlias(false, false, grammarAccess.getGithubActionsAccess().getJobsKeyword_2_0()), new TokenAlias(false, false, grammarAccess.getGithubActionsAccess().getColonKeyword_2_1()), new TokenAlias(false, false, grammarAccess.getGithubActionsAccess().getBEG_BLOCKTerminalRuleCall_2_2()));
		match_Job___END_BLOCKTerminalRuleCall_3_1_2_0_2_NeedsKeyword_3_1_0_ColonKeyword_3_1_1_BEG_BLOCKTerminalRuleCall_3_1_2_0_0__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getJobAccess().getEND_BLOCKTerminalRuleCall_3_1_2_0_2()), new TokenAlias(false, false, grammarAccess.getJobAccess().getNeedsKeyword_3_1_0()), new TokenAlias(false, false, grammarAccess.getJobAccess().getColonKeyword_3_1_1()), new TokenAlias(false, false, grammarAccess.getJobAccess().getBEG_BLOCKTerminalRuleCall_3_1_2_0_0()));
		match_Job___END_BLOCKTerminalRuleCall_3_2_4_StepsKeyword_3_2_0_ColonKeyword_3_2_1_BEG_BLOCKTerminalRuleCall_3_2_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getJobAccess().getEND_BLOCKTerminalRuleCall_3_2_4()), new TokenAlias(false, false, grammarAccess.getJobAccess().getStepsKeyword_3_2_0()), new TokenAlias(false, false, grammarAccess.getJobAccess().getColonKeyword_3_2_1()), new TokenAlias(false, false, grammarAccess.getJobAccess().getBEG_BLOCKTerminalRuleCall_3_2_2()));
		match_Push___END_BLOCKTerminalRuleCall_2_0_2_0_2_BranchesKeyword_2_0_0_ColonKeyword_2_0_1_BEG_BLOCKTerminalRuleCall_2_0_2_0_0__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPushAccess().getEND_BLOCKTerminalRuleCall_2_0_2_0_2()), new TokenAlias(false, false, grammarAccess.getPushAccess().getBranchesKeyword_2_0_0()), new TokenAlias(false, false, grammarAccess.getPushAccess().getColonKeyword_2_0_1()), new TokenAlias(false, false, grammarAccess.getPushAccess().getBEG_BLOCKTerminalRuleCall_2_0_2_0_0()));
		match_Push___END_BLOCKTerminalRuleCall_2_1_2_0_2_TagsKeyword_2_1_0_ColonKeyword_2_1_1_BEG_BLOCKTerminalRuleCall_2_1_2_0_0__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPushAccess().getEND_BLOCKTerminalRuleCall_2_1_2_0_2()), new TokenAlias(false, false, grammarAccess.getPushAccess().getTagsKeyword_2_1_0()), new TokenAlias(false, false, grammarAccess.getPushAccess().getColonKeyword_2_1_1()), new TokenAlias(false, false, grammarAccess.getPushAccess().getBEG_BLOCKTerminalRuleCall_2_1_2_0_0()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getBEG_BLOCKRule())
			return getBEG_BLOCKToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getEND_BLOCKRule())
			return getEND_BLOCKToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * terminal BEG_BLOCK: 'synthetic:BEGIN';
	 */
	protected String getBEG_BLOCKToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "synthetic:BEGIN";
	}
	
	/**
	 * terminal END_BLOCK: 'synthetic:END';
	 */
	protected String getEND_BLOCKToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "synthetic:END";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_GithubActions___END_BLOCKTerminalRuleCall_2_4_JobsKeyword_2_0_ColonKeyword_2_1_BEG_BLOCKTerminalRuleCall_2_2__q.equals(syntax))
				emit_GithubActions___END_BLOCKTerminalRuleCall_2_4_JobsKeyword_2_0_ColonKeyword_2_1_BEG_BLOCKTerminalRuleCall_2_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Job___END_BLOCKTerminalRuleCall_3_1_2_0_2_NeedsKeyword_3_1_0_ColonKeyword_3_1_1_BEG_BLOCKTerminalRuleCall_3_1_2_0_0__q.equals(syntax))
				emit_Job___END_BLOCKTerminalRuleCall_3_1_2_0_2_NeedsKeyword_3_1_0_ColonKeyword_3_1_1_BEG_BLOCKTerminalRuleCall_3_1_2_0_0__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Job___END_BLOCKTerminalRuleCall_3_2_4_StepsKeyword_3_2_0_ColonKeyword_3_2_1_BEG_BLOCKTerminalRuleCall_3_2_2__q.equals(syntax))
				emit_Job___END_BLOCKTerminalRuleCall_3_2_4_StepsKeyword_3_2_0_ColonKeyword_3_2_1_BEG_BLOCKTerminalRuleCall_3_2_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Push___END_BLOCKTerminalRuleCall_2_0_2_0_2_BranchesKeyword_2_0_0_ColonKeyword_2_0_1_BEG_BLOCKTerminalRuleCall_2_0_2_0_0__q.equals(syntax))
				emit_Push___END_BLOCKTerminalRuleCall_2_0_2_0_2_BranchesKeyword_2_0_0_ColonKeyword_2_0_1_BEG_BLOCKTerminalRuleCall_2_0_2_0_0__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Push___END_BLOCKTerminalRuleCall_2_1_2_0_2_TagsKeyword_2_1_0_ColonKeyword_2_1_1_BEG_BLOCKTerminalRuleCall_2_1_2_0_0__q.equals(syntax))
				emit_Push___END_BLOCKTerminalRuleCall_2_1_2_0_2_TagsKeyword_2_1_0_ColonKeyword_2_1_1_BEG_BLOCKTerminalRuleCall_2_1_2_0_0__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK 'jobs' ':' BEG_BLOCK)?
	 *
	 * This ambiguous syntax occurs at:
	 *     jobs+=Job (ambiguity) jobs+=Job
	 
	 * </pre>
	 */
	protected void emit_GithubActions___END_BLOCKTerminalRuleCall_2_4_JobsKeyword_2_0_ColonKeyword_2_1_BEG_BLOCKTerminalRuleCall_2_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK 'needs' ':' BEG_BLOCK)?
	 *
	 * This ambiguous syntax occurs at:
	 *     needs+=EString END_BLOCK (ambiguity) '-' BEG_BLOCK needs+=EString
	 
	 * </pre>
	 */
	protected void emit_Job___END_BLOCKTerminalRuleCall_3_1_2_0_2_NeedsKeyword_3_1_0_ColonKeyword_3_1_1_BEG_BLOCKTerminalRuleCall_3_1_2_0_0__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK 'steps' ':' BEG_BLOCK)?
	 *
	 * This ambiguous syntax occurs at:
	 *     steps+=Step (ambiguity) steps+=Step
	 
	 * </pre>
	 */
	protected void emit_Job___END_BLOCKTerminalRuleCall_3_2_4_StepsKeyword_3_2_0_ColonKeyword_3_2_1_BEG_BLOCKTerminalRuleCall_3_2_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK 'branches' ':' BEG_BLOCK)?
	 *
	 * This ambiguous syntax occurs at:
	 *     branches+=EString END_BLOCK (ambiguity) '-' BEG_BLOCK branches+=EString
	 
	 * </pre>
	 */
	protected void emit_Push___END_BLOCKTerminalRuleCall_2_0_2_0_2_BranchesKeyword_2_0_0_ColonKeyword_2_0_1_BEG_BLOCKTerminalRuleCall_2_0_2_0_0__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * <pre>
	 * Ambiguous syntax:
	 *     (END_BLOCK 'tags' ':' BEG_BLOCK)?
	 *
	 * This ambiguous syntax occurs at:
	 *     tags+=EString END_BLOCK (ambiguity) '-' BEG_BLOCK tags+=EString
	 
	 * </pre>
	 */
	protected void emit_Push___END_BLOCKTerminalRuleCall_2_1_2_0_2_TagsKeyword_2_1_0_ColonKeyword_2_1_1_BEG_BLOCKTerminalRuleCall_2_1_2_0_0__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
