/*
 * generated by Xtext 2.42.0
 */
package pt.isep.yamldslgen.xtext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import pt.isep.yamldslgen.github_actions.Concurrency;
import pt.isep.yamldslgen.github_actions.Environment;
import pt.isep.yamldslgen.github_actions.GithubActions;
import pt.isep.yamldslgen.github_actions.Job;
import pt.isep.yamldslgen.github_actions.KeyValuePair;
import pt.isep.yamldslgen.github_actions.On;
import pt.isep.yamldslgen.github_actions.Permissions;
import pt.isep.yamldslgen.github_actions.Pull_request;
import pt.isep.yamldslgen.github_actions.Push;
import pt.isep.yamldslgen.github_actions.Schedule;
import pt.isep.yamldslgen.github_actions.Step;
import pt.isep.yamldslgen.github_actions.YamlmdePackage;
import pt.isep.yamldslgen.xtext.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == YamlmdePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case YamlmdePackage.CONCURRENCY:
				sequence_Concurrency(context, (Concurrency) semanticObject); 
				return; 
			case YamlmdePackage.ENVIRONMENT:
				sequence_Environment(context, (Environment) semanticObject); 
				return; 
			case YamlmdePackage.GITHUB_ACTIONS:
				sequence_GithubActions(context, (GithubActions) semanticObject); 
				return; 
			case YamlmdePackage.JOB:
				sequence_Job(context, (Job) semanticObject); 
				return; 
			case YamlmdePackage.KEY_VALUE_PAIR:
				sequence_KeyValuePair(context, (KeyValuePair) semanticObject); 
				return; 
			case YamlmdePackage.ON:
				sequence_On(context, (On) semanticObject); 
				return; 
			case YamlmdePackage.PERMISSIONS:
				sequence_Permissions(context, (Permissions) semanticObject); 
				return; 
			case YamlmdePackage.PULL_REQUEST:
				sequence_Pull_request(context, (Pull_request) semanticObject); 
				return; 
			case YamlmdePackage.PUSH:
				sequence_Push(context, (Push) semanticObject); 
				return; 
			case YamlmdePackage.SCHEDULE:
				sequence_Schedule(context, (Schedule) semanticObject); 
				return; 
			case YamlmdePackage.STEP:
				sequence_Step(context, (Step) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Concurrency returns Concurrency
	 *
	 * Constraint:
	 *     (group=EString | cancelInProgress=EBoolean)*
	 * </pre>
	 */
	protected void sequence_Concurrency(ISerializationContext context, Concurrency semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Environment returns Environment
	 *
	 * Constraint:
	 *     (name=EString | url=EString)*
	 * </pre>
	 */
	protected void sequence_Environment(ISerializationContext context, Environment semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     GithubActions returns GithubActions
	 *
	 * Constraint:
	 *     (
	 *         name=EString | 
	 *         on=On | 
	 *         concurrency=Concurrency | 
	 *         jobs+=Job | 
	 *         permissions=Permissions | 
	 *         env+=KeyValuePair
	 *     )+
	 * </pre>
	 */
	protected void sequence_GithubActions(ISerializationContext context, GithubActions semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Job returns Job
	 *
	 * Constraint:
	 *     (
	 *         id=EString 
	 *         (
	 *             (
	 *                 name=EString | 
	 *                 runsOn=EString | 
	 *                 needs+=EString | 
	 *                 needs+=EString | 
	 *                 if=EString | 
	 *                 environment=Environment | 
	 *                 steps+=Step | 
	 *                 permissions=Permissions
	 *             )? 
	 *             (needs+=EString needs+=EString*)?
	 *         )+
	 *     )
	 * </pre>
	 */
	protected void sequence_Job(ISerializationContext context, Job semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     KeyValuePair returns KeyValuePair
	 *
	 * Constraint:
	 *     (key=KeyName value=EString)
	 * </pre>
	 */
	protected void sequence_KeyValuePair(ISerializationContext context, KeyValuePair semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlmdePackage.Literals.KEY_VALUE_PAIR__KEY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlmdePackage.Literals.KEY_VALUE_PAIR__KEY));
			if (transientValues.isValueTransient(semanticObject, YamlmdePackage.Literals.KEY_VALUE_PAIR__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlmdePackage.Literals.KEY_VALUE_PAIR__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getKeyValuePairAccess().getKeyKeyNameParserRuleCall_0_0(), semanticObject.getKey());
		feeder.accept(grammarAccess.getKeyValuePairAccess().getValueEStringParserRuleCall_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     On returns On
	 *
	 * Constraint:
	 *     (push=Push | pullRequest=Pull_request | schedule+=Schedule | workflowDispatch=EString)*
	 * </pre>
	 */
	protected void sequence_On(ISerializationContext context, On semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Permissions returns Permissions
	 *
	 * Constraint:
	 *     (
	 *         contents=EString | 
	 *         securityEvents=EString | 
	 *         actions=EString | 
	 *         pages=EString | 
	 *         idToken=EString | 
	 *         pullRequests=EString | 
	 *         issues=EString
	 *     )*
	 * </pre>
	 */
	protected void sequence_Permissions(ISerializationContext context, Permissions semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Pull_request returns Pull_request
	 *
	 * Constraint:
	 *     ((branches+=EString | types+=EString)? (branches+=EString branches+=EString*)? (types+=EString types+=EString*)?)+
	 * </pre>
	 */
	protected void sequence_Pull_request(ISerializationContext context, Pull_request semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Push returns Push
	 *
	 * Constraint:
	 *     ((branches+=EString | tags+=EString)? (branches+=EString branches+=EString*)? (tags+=EString tags+=EString*)?)+
	 * </pre>
	 */
	protected void sequence_Push(ISerializationContext context, Push semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Schedule returns Schedule
	 *
	 * Constraint:
	 *     cron=EString
	 * </pre>
	 */
	protected void sequence_Schedule(ISerializationContext context, Schedule semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlmdePackage.Literals.SCHEDULE__CRON) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlmdePackage.Literals.SCHEDULE__CRON));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getScheduleAccess().getCronEStringParserRuleCall_4_0(), semanticObject.getCron());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Step returns Step
	 *
	 * Constraint:
	 *     (
	 *         name=EString | 
	 *         id=EString | 
	 *         uses=EString | 
	 *         run=EString | 
	 *         if=EString | 
	 *         workingDirectory=EString | 
	 *         shell=EString | 
	 *         continueOnError=EBoolean | 
	 *         with+=KeyValuePair | 
	 *         env+=KeyValuePair
	 *     )*
	 * </pre>
	 */
	protected void sequence_Step(ISerializationContext context, Step semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
