/*
 * generated by Xtext 2.42.0
 */
package pt.isep.yamldslgen.xtext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import pt.isep.yamldslgen.github_actions.Concurrency;
import pt.isep.yamldslgen.github_actions.Container;
import pt.isep.yamldslgen.github_actions.Defaults;
import pt.isep.yamldslgen.github_actions.EnvironmentObject;
import pt.isep.yamldslgen.github_actions.EnvironmentValue;
import pt.isep.yamldslgen.github_actions.Exclude;
import pt.isep.yamldslgen.github_actions.GithubActions;
import pt.isep.yamldslgen.github_actions.Include;
import pt.isep.yamldslgen.github_actions.Input;
import pt.isep.yamldslgen.github_actions.Issues;
import pt.isep.yamldslgen.github_actions.Job;
import pt.isep.yamldslgen.github_actions.KeyValuePair;
import pt.isep.yamldslgen.github_actions.MatrixObject;
import pt.isep.yamldslgen.github_actions.MatrixParameter;
import pt.isep.yamldslgen.github_actions.MatrixValue;
import pt.isep.yamldslgen.github_actions.Merge_group;
import pt.isep.yamldslgen.github_actions.OnObject;
import pt.isep.yamldslgen.github_actions.OnValue;
import pt.isep.yamldslgen.github_actions.PermissionsObject;
import pt.isep.yamldslgen.github_actions.PermissionsValue;
import pt.isep.yamldslgen.github_actions.Pull_request;
import pt.isep.yamldslgen.github_actions.Push;
import pt.isep.yamldslgen.github_actions.Release;
import pt.isep.yamldslgen.github_actions.Run;
import pt.isep.yamldslgen.github_actions.Schedule;
import pt.isep.yamldslgen.github_actions.Secret;
import pt.isep.yamldslgen.github_actions.Service;
import pt.isep.yamldslgen.github_actions.Step;
import pt.isep.yamldslgen.github_actions.Strategy;
import pt.isep.yamldslgen.github_actions.Workflow_call;
import pt.isep.yamldslgen.github_actions.Workflow_dispatch;
import pt.isep.yamldslgen.github_actions.YamlmdePackage;
import pt.isep.yamldslgen.xtext.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == YamlmdePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case YamlmdePackage.CONCURRENCY:
				sequence_Concurrency(context, (Concurrency) semanticObject); 
				return; 
			case YamlmdePackage.CONTAINER:
				sequence_Container(context, (Container) semanticObject); 
				return; 
			case YamlmdePackage.DEFAULTS:
				sequence_Defaults(context, (Defaults) semanticObject); 
				return; 
			case YamlmdePackage.ENVIRONMENT_OBJECT:
				sequence_EnvironmentObject(context, (EnvironmentObject) semanticObject); 
				return; 
			case YamlmdePackage.ENVIRONMENT_VALUE:
				sequence_EnvironmentValue(context, (EnvironmentValue) semanticObject); 
				return; 
			case YamlmdePackage.EXCLUDE:
				sequence_Exclude(context, (Exclude) semanticObject); 
				return; 
			case YamlmdePackage.GITHUB_ACTIONS:
				sequence_GithubActions(context, (GithubActions) semanticObject); 
				return; 
			case YamlmdePackage.INCLUDE:
				sequence_Include(context, (Include) semanticObject); 
				return; 
			case YamlmdePackage.INPUT:
				sequence_Input(context, (Input) semanticObject); 
				return; 
			case YamlmdePackage.ISSUES:
				sequence_Issues(context, (Issues) semanticObject); 
				return; 
			case YamlmdePackage.JOB:
				sequence_Job(context, (Job) semanticObject); 
				return; 
			case YamlmdePackage.KEY_VALUE_PAIR:
				sequence_KeyValuePair(context, (KeyValuePair) semanticObject); 
				return; 
			case YamlmdePackage.MATRIX_OBJECT:
				sequence_MatrixObject(context, (MatrixObject) semanticObject); 
				return; 
			case YamlmdePackage.MATRIX_PARAMETER:
				sequence_MatrixParameter(context, (MatrixParameter) semanticObject); 
				return; 
			case YamlmdePackage.MATRIX_VALUE:
				sequence_MatrixValue(context, (MatrixValue) semanticObject); 
				return; 
			case YamlmdePackage.MERGE_GROUP:
				sequence_Merge_group(context, (Merge_group) semanticObject); 
				return; 
			case YamlmdePackage.ON_OBJECT:
				sequence_OnObject(context, (OnObject) semanticObject); 
				return; 
			case YamlmdePackage.ON_VALUE:
				sequence_OnValue(context, (OnValue) semanticObject); 
				return; 
			case YamlmdePackage.PERMISSIONS_OBJECT:
				sequence_PermissionsObject(context, (PermissionsObject) semanticObject); 
				return; 
			case YamlmdePackage.PERMISSIONS_VALUE:
				sequence_PermissionsValue(context, (PermissionsValue) semanticObject); 
				return; 
			case YamlmdePackage.PULL_REQUEST:
				sequence_Pull_request(context, (Pull_request) semanticObject); 
				return; 
			case YamlmdePackage.PUSH:
				sequence_Push(context, (Push) semanticObject); 
				return; 
			case YamlmdePackage.RELEASE:
				sequence_Release(context, (Release) semanticObject); 
				return; 
			case YamlmdePackage.RUN:
				sequence_Run(context, (Run) semanticObject); 
				return; 
			case YamlmdePackage.SCHEDULE:
				sequence_Schedule(context, (Schedule) semanticObject); 
				return; 
			case YamlmdePackage.SECRET:
				sequence_Secret(context, (Secret) semanticObject); 
				return; 
			case YamlmdePackage.SERVICE:
				sequence_Service(context, (Service) semanticObject); 
				return; 
			case YamlmdePackage.STEP:
				sequence_Step(context, (Step) semanticObject); 
				return; 
			case YamlmdePackage.STRATEGY:
				sequence_Strategy(context, (Strategy) semanticObject); 
				return; 
			case YamlmdePackage.WORKFLOW_CALL:
				sequence_Workflow_call(context, (Workflow_call) semanticObject); 
				return; 
			case YamlmdePackage.WORKFLOW_DISPATCH:
				sequence_Workflow_dispatch(context, (Workflow_dispatch) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Concurrency returns Concurrency
	 *
	 * Constraint:
	 *     (group=EString | cancelInProgress=EBoolean)*
	 * </pre>
	 */
	protected void sequence_Concurrency(ISerializationContext context, Concurrency semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Container returns Container
	 *
	 * Constraint:
	 *     image=EString
	 * </pre>
	 */
	protected void sequence_Container(ISerializationContext context, Container semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlmdePackage.Literals.CONTAINER__IMAGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlmdePackage.Literals.CONTAINER__IMAGE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getContainerAccess().getImageEStringParserRuleCall_2_2_0(), semanticObject.getImage());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Defaults returns Defaults
	 *
	 * Constraint:
	 *     run=Run
	 * </pre>
	 */
	protected void sequence_Defaults(ISerializationContext context, Defaults semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlmdePackage.Literals.DEFAULTS__RUN) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlmdePackage.Literals.DEFAULTS__RUN));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDefaultsAccess().getRunRunParserRuleCall_2_2_0(), semanticObject.getRun());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Environment returns EnvironmentObject
	 *     EnvironmentObject returns EnvironmentObject
	 *
	 * Constraint:
	 *     (name=EString | url=EString)*
	 * </pre>
	 */
	protected void sequence_EnvironmentObject(ISerializationContext context, EnvironmentObject semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Environment returns EnvironmentValue
	 *     EnvironmentValue returns EnvironmentValue
	 *
	 * Constraint:
	 *     value=EString
	 * </pre>
	 */
	protected void sequence_EnvironmentValue(ISerializationContext context, EnvironmentValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlmdePackage.Literals.ENVIRONMENT_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlmdePackage.Literals.ENVIRONMENT_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEnvironmentValueAccess().getValueEStringParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Exclude returns Exclude
	 *
	 * Constraint:
	 *     entries+=KeyValuePair+
	 * </pre>
	 */
	protected void sequence_Exclude(ISerializationContext context, Exclude semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     GithubActions returns GithubActions
	 *
	 * Constraint:
	 *     (
	 *         name=EString | 
	 *         on=On | 
	 *         concurrency=Concurrency | 
	 *         defaults=Defaults | 
	 *         jobs+=Job | 
	 *         permissions=Permissions | 
	 *         env+=KeyValuePair
	 *     )+
	 * </pre>
	 */
	protected void sequence_GithubActions(ISerializationContext context, GithubActions semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Include returns Include
	 *
	 * Constraint:
	 *     entries+=KeyValuePair+
	 * </pre>
	 */
	protected void sequence_Include(ISerializationContext context, Include semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Input returns Input
	 *
	 * Constraint:
	 *     (id=KeyName (description=EString | default=EString | required=EBoolean | type=EString)*)
	 * </pre>
	 */
	protected void sequence_Input(ISerializationContext context, Input semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Issues returns Issues
	 *
	 * Constraint:
	 *     (types+=EString+ | (types+=EString types+=EString*))
	 * </pre>
	 */
	protected void sequence_Issues(ISerializationContext context, Issues semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Job returns Job
	 *
	 * Constraint:
	 *     (
	 *         id=EString 
	 *         (
	 *             (
	 *                 name=EString | 
	 *                 runsOn=EString | 
	 *                 needs+=EString | 
	 *                 needs+=EString | 
	 *                 if=EString | 
	 *                 uses=EString | 
	 *                 environment=Environment | 
	 *                 strategy=Strategy | 
	 *                 container=Container | 
	 *                 services+=Service | 
	 *                 outputs+=KeyValuePair | 
	 *                 defaults=Defaults | 
	 *                 steps+=Step | 
	 *                 permissions=Permissions | 
	 *                 env+=KeyValuePair | 
	 *                 with+=KeyValuePair
	 *             )? 
	 *             (needs+=EString needs+=EString*)?
	 *         )+
	 *     )
	 * </pre>
	 */
	protected void sequence_Job(ISerializationContext context, Job semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     KeyValuePair returns KeyValuePair
	 *
	 * Constraint:
	 *     (key=KeyName value=EString)
	 * </pre>
	 */
	protected void sequence_KeyValuePair(ISerializationContext context, KeyValuePair semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlmdePackage.Literals.KEY_VALUE_PAIR__KEY) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlmdePackage.Literals.KEY_VALUE_PAIR__KEY));
			if (transientValues.isValueTransient(semanticObject, YamlmdePackage.Literals.KEY_VALUE_PAIR__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlmdePackage.Literals.KEY_VALUE_PAIR__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getKeyValuePairAccess().getKeyKeyNameParserRuleCall_0_0(), semanticObject.getKey());
		feeder.accept(grammarAccess.getKeyValuePairAccess().getValueEStringParserRuleCall_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Matrix returns MatrixObject
	 *     MatrixObject returns MatrixObject
	 *
	 * Constraint:
	 *     (include+=Include | exclude+=Exclude | parameters+=MatrixParameter)*
	 * </pre>
	 */
	protected void sequence_MatrixObject(ISerializationContext context, MatrixObject semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     MatrixParameter returns MatrixParameter
	 *
	 * Constraint:
	 *     (key=KeyName (values+=EString+ | (values+=EString values+=EString*)))
	 * </pre>
	 */
	protected void sequence_MatrixParameter(ISerializationContext context, MatrixParameter semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Matrix returns MatrixValue
	 *     MatrixValue returns MatrixValue
	 *
	 * Constraint:
	 *     value=EString
	 * </pre>
	 */
	protected void sequence_MatrixValue(ISerializationContext context, MatrixValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlmdePackage.Literals.MATRIX_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlmdePackage.Literals.MATRIX_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMatrixValueAccess().getValueEStringParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Merge_group returns Merge_group
	 *
	 * Constraint:
	 *     (branches+=EString+ | (branches+=EString branches+=EString*))
	 * </pre>
	 */
	protected void sequence_Merge_group(ISerializationContext context, Merge_group semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     On returns OnObject
	 *     OnObject returns OnObject
	 *
	 * Constraint:
	 *     (
	 *         branchProtectionRule=EString | 
	 *         push=Push | 
	 *         pullRequest=Pull_request | 
	 *         pullRequestTarget=Pull_request | 
	 *         schedule+=Schedule | 
	 *         workflowDispatch=Workflow_dispatch | 
	 *         workflowCall=Workflow_call | 
	 *         release=Release | 
	 *         mergeGroup=Merge_group | 
	 *         issues=Issues
	 *     )*
	 * </pre>
	 */
	protected void sequence_OnObject(ISerializationContext context, OnObject semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     On returns OnValue
	 *     OnValue returns OnValue
	 *
	 * Constraint:
	 *     (value+=EString | (value+=EString value+=EString*))
	 * </pre>
	 */
	protected void sequence_OnValue(ISerializationContext context, OnValue semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Permissions returns PermissionsObject
	 *     PermissionsObject returns PermissionsObject
	 *
	 * Constraint:
	 *     (
	 *         contents=EString | 
	 *         securityEvents=EString | 
	 *         actions=EString | 
	 *         pages=EString | 
	 *         idToken=EString | 
	 *         pullRequests=EString | 
	 *         issues=EString | 
	 *         packages=EString | 
	 *         models=EString | 
	 *         checks=EString
	 *     )*
	 * </pre>
	 */
	protected void sequence_PermissionsObject(ISerializationContext context, PermissionsObject semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Permissions returns PermissionsValue
	 *     PermissionsValue returns PermissionsValue
	 *
	 * Constraint:
	 *     value=EString
	 * </pre>
	 */
	protected void sequence_PermissionsValue(ISerializationContext context, PermissionsValue semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlmdePackage.Literals.PERMISSIONS_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlmdePackage.Literals.PERMISSIONS_VALUE__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPermissionsValueAccess().getValueEStringParserRuleCall_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Pull_request returns Pull_request
	 *
	 * Constraint:
	 *     ((branches+=EString | types+=EString)? (branches+=EString branches+=EString*)? (types+=EString types+=EString*)?)+
	 * </pre>
	 */
	protected void sequence_Pull_request(ISerializationContext context, Pull_request semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Push returns Push
	 *
	 * Constraint:
	 *     ((branches+=EString | tags+=EString)? (branches+=EString branches+=EString*)? (tags+=EString tags+=EString*)?)+
	 * </pre>
	 */
	protected void sequence_Push(ISerializationContext context, Push semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Release returns Release
	 *
	 * Constraint:
	 *     (types+=EString+ | (types+=EString types+=EString*))
	 * </pre>
	 */
	protected void sequence_Release(ISerializationContext context, Release semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Run returns Run
	 *
	 * Constraint:
	 *     shell=EString
	 * </pre>
	 */
	protected void sequence_Run(ISerializationContext context, Run semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlmdePackage.Literals.RUN__SHELL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlmdePackage.Literals.RUN__SHELL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRunAccess().getShellEStringParserRuleCall_2_2_0(), semanticObject.getShell());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Schedule returns Schedule
	 *
	 * Constraint:
	 *     cron=EString
	 * </pre>
	 */
	protected void sequence_Schedule(ISerializationContext context, Schedule semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, YamlmdePackage.Literals.SCHEDULE__CRON) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, YamlmdePackage.Literals.SCHEDULE__CRON));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getScheduleAccess().getCronEStringParserRuleCall_4_0(), semanticObject.getCron());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Secret returns Secret
	 *
	 * Constraint:
	 *     (id=EString required=EBoolean?)
	 * </pre>
	 */
	protected void sequence_Secret(ISerializationContext context, Secret semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Service returns Service
	 *
	 * Constraint:
	 *     (id=EString ((image=EString | ports+=EString | env+=KeyValuePair)? (ports+=EString ports+=EString*)?)+)
	 * </pre>
	 */
	protected void sequence_Service(ISerializationContext context, Service semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Step returns Step
	 *
	 * Constraint:
	 *     (
	 *         name=EString | 
	 *         id=EString | 
	 *         uses=EString | 
	 *         run=EString | 
	 *         if=EString | 
	 *         workingDirectory=EString | 
	 *         shell=EString | 
	 *         continueOnError=EBoolean | 
	 *         timeoutMinutes=INT | 
	 *         with+=KeyValuePair | 
	 *         env+=KeyValuePair
	 *     )*
	 * </pre>
	 */
	protected void sequence_Step(ISerializationContext context, Step semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Strategy returns Strategy
	 *
	 * Constraint:
	 *     (failFast=EBoolean | maxParallel=INT | matrix=Matrix)*
	 * </pre>
	 */
	protected void sequence_Strategy(ISerializationContext context, Strategy semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Workflow_call returns Workflow_call
	 *
	 * Constraint:
	 *     secrets+=Secret*
	 * </pre>
	 */
	protected void sequence_Workflow_call(ISerializationContext context, Workflow_call semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Workflow_dispatch returns Workflow_dispatch
	 *
	 * Constraint:
	 *     inputs+=Input*
	 * </pre>
	 */
	protected void sequence_Workflow_dispatch(ISerializationContext context, Workflow_dispatch semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
