/**
 * generated by Xtext 2.42.0
 */
package pt.isep.yamldslgen.xtext.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.XbaseGenerated;
import pt.isep.yamldslgen.github_actions.GithubActions;
import pt.isep.yamldslgen.github_actions.Job;
import pt.isep.yamldslgen.github_actions.On;
import pt.isep.yamldslgen.github_actions.Pull_request;
import pt.isep.yamldslgen.github_actions.Push;
import pt.isep.yamldslgen.xtext.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;

  protected void _format(final GithubActions githubActions, @Extension final IFormattableDocument document) {
    document.<On>format(githubActions.getOn());
    EList<Job> _jobs = githubActions.getJobs();
    for (final Job job : _jobs) {
      document.<Job>format(job);
    }
  }

  protected void _format(final On on, @Extension final IFormattableDocument document) {
    document.<Push>format(on.getPush());
    document.<Pull_request>format(on.getPullRequest());
  }

  @XbaseGenerated
  public void format(final Object githubActions, final IFormattableDocument document) {
    if (githubActions instanceof XtextResource) {
      _format((XtextResource)githubActions, document);
      return;
    } else if (githubActions instanceof GithubActions) {
      _format((GithubActions)githubActions, document);
      return;
    } else if (githubActions instanceof On) {
      _format((On)githubActions, document);
      return;
    } else if (githubActions instanceof EObject) {
      _format((EObject)githubActions, document);
      return;
    } else if (githubActions == null) {
      _format((Void)null, document);
      return;
    } else if (githubActions != null) {
      _format(githubActions, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(githubActions, document).toString());
    }
  }
}
