#

pluginName = pt.isep.yamldslgen.dockercompose Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_KeyValuePair_type = Key Value Pair
_UI_DockerCompose_type = Docker Compose
_UI_Service_type = Service
_UI_Build_type = Build
_UI_Healthcheck_type = Healthcheck
_UI_Networks_type = Networks
_UI_Network_type = Network
_UI_Volume_type = Volume
_UI_Resource_type = Resource
_UI_Secret_type = Secret
_UI_Depends_on_type = Depends on
_UI_Db_type = Db
_UI_Config_type = Config
_UI_VolumeObject_type = Volume Object
_UI_VolumeValue_type = Volume Value
_UI_BuildObject_type = Build Object
_UI_BuildValue_type = Build Value
_UI_NetworksObject_type = Networks Object
_UI_NetworksValue_type = Networks Value
_UI_Depends_onObject_type = Depends on Object
_UI_Depends_onValue_type = Depends on Value
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_KeyValuePair_key_feature = Key
_UI_KeyValuePair_value_feature = Value
_UI_DockerCompose_version_feature = Version
_UI_DockerCompose_name_feature = Name
_UI_DockerCompose_services_feature = Services
_UI_DockerCompose_networks_feature = Networks
_UI_DockerCompose_volumes_feature = Volumes
_UI_DockerCompose_secrets_feature = Secrets
_UI_Service_id_feature = Id
_UI_Service_ports_feature = Ports
_UI_Service_image_feature = Image
_UI_Service_restart_feature = Restart
_UI_Service_containerName_feature = Container Name
_UI_Service_command_feature = Command
_UI_Service_stopSignal_feature = Stop Signal
_UI_Service_expose_feature = Expose
_UI_Service_secrets_feature = Secrets
_UI_Service_user_feature = User
_UI_Service_hostname_feature = Hostname
_UI_Service_capAdd_feature = Cap Add
_UI_Service_networkMode_feature = Network Mode
_UI_Service_stdinOpen_feature = Stdin Open
_UI_Service_labels_feature = Labels
_UI_Service_platform_feature = Platform
_UI_Service_runtime_feature = Runtime
_UI_Service_sysctls_feature = Sysctls
_UI_Service_build_feature = Build
_UI_Service_healthcheck_feature = Healthcheck
_UI_Service_deploy_feature = Deploy
_UI_Service_dependsOn_feature = Depends On
_UI_Service_volumes_feature = Volumes
_UI_Service_networks_feature = Networks
_UI_Service_environment_feature = Environment
_UI_Healthcheck_test_feature = Test
_UI_Healthcheck_interval_feature = Interval
_UI_Healthcheck_retries_feature = Retries
_UI_Healthcheck_startPeriod_feature = Start Period
_UI_Healthcheck_timeout_feature = Timeout
_UI_Network_id_feature = Id
_UI_Network_driver_feature = Driver
_UI_Network_ipv4Address_feature = Ipv4 Address
_UI_Network_ipam_feature = Ipam
_UI_Resource_id_feature = Id
_UI_Resource_memory_feature = Memory
_UI_Secret_id_feature = Id
_UI_Secret_file_feature = File
_UI_Db_condition_feature = Condition
_UI_Config_subnet_feature = Subnet
_UI_VolumeObject_id_feature = Id
_UI_VolumeObject_type_feature = Type
_UI_VolumeObject_source_feature = Source
_UI_VolumeObject_target_feature = Target
_UI_VolumeObject_readOnly_feature = Read Only
_UI_VolumeValue_value_feature = Value
_UI_BuildObject_context_feature = Context
_UI_BuildObject_target_feature = Target
_UI_BuildObject_args_feature = Args
_UI_BuildObject_dockerfile_feature = Dockerfile
_UI_BuildValue_value_feature = Value
_UI_NetworksObject_network_feature = Network
_UI_NetworksValue_value_feature = Value
_UI_Depends_onObject_db_feature = Db
_UI_Depends_onValue_value_feature = Value
_UI_Unknown_feature = Unspecified

