/*
 * generated by Xtext 2.42.0
 */
package pt.isep.yamldslgen.dockercompose.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import pt.isep.yamldslgen.dockercompose.xtext.DcDslRuntimeModule;
import pt.isep.yamldslgen.dockercompose.xtext.DcDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DcDslIdeSetup extends DcDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DcDslRuntimeModule(), new DcDslIdeModule()));
	}
	
}
