/**
 */
package pt.isep.yamldslgen.github_actions.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import pt.isep.yamldslgen.github_actions.util.YamlmdeAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class YamlmdeItemProviderAdapterFactory extends YamlmdeAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public YamlmdeItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.KeyValuePair} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected KeyValuePairItemProvider keyValuePairItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.KeyValuePair}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createKeyValuePairAdapter() {
		if (keyValuePairItemProvider == null) {
			keyValuePairItemProvider = new KeyValuePairItemProvider(this);
		}

		return keyValuePairItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.GithubActions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GithubActionsItemProvider githubActionsItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.GithubActions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGithubActionsAdapter() {
		if (githubActionsItemProvider == null) {
			githubActionsItemProvider = new GithubActionsItemProvider(this);
		}

		return githubActionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Job} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected JobItemProvider jobItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Job}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createJobAdapter() {
		if (jobItemProvider == null) {
			jobItemProvider = new JobItemProvider(this);
		}

		return jobItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Step} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StepItemProvider stepItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Step}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStepAdapter() {
		if (stepItemProvider == null) {
			stepItemProvider = new StepItemProvider(this);
		}

		return stepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.On} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OnItemProvider onItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.On}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOnAdapter() {
		if (onItemProvider == null) {
			onItemProvider = new OnItemProvider(this);
		}

		return onItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Push} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PushItemProvider pushItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Push}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPushAdapter() {
		if (pushItemProvider == null) {
			pushItemProvider = new PushItemProvider(this);
		}

		return pushItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Pull_request} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Pull_requestItemProvider pull_requestItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Pull_request}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPull_requestAdapter() {
		if (pull_requestItemProvider == null) {
			pull_requestItemProvider = new Pull_requestItemProvider(this);
		}

		return pull_requestItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Permissions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PermissionsItemProvider permissionsItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Permissions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPermissionsAdapter() {
		if (permissionsItemProvider == null) {
			permissionsItemProvider = new PermissionsItemProvider(this);
		}

		return permissionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Schedule} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ScheduleItemProvider scheduleItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Schedule}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createScheduleAdapter() {
		if (scheduleItemProvider == null) {
			scheduleItemProvider = new ScheduleItemProvider(this);
		}

		return scheduleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Workflow_dispatch} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Workflow_dispatchItemProvider workflow_dispatchItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Workflow_dispatch}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkflow_dispatchAdapter() {
		if (workflow_dispatchItemProvider == null) {
			workflow_dispatchItemProvider = new Workflow_dispatchItemProvider(this);
		}

		return workflow_dispatchItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Environment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnvironmentItemProvider environmentItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Environment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnvironmentAdapter() {
		if (environmentItemProvider == null) {
			environmentItemProvider = new EnvironmentItemProvider(this);
		}

		return environmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Concurrency} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConcurrencyItemProvider concurrencyItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Concurrency}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConcurrencyAdapter() {
		if (concurrencyItemProvider == null) {
			concurrencyItemProvider = new ConcurrencyItemProvider(this);
		}

		return concurrencyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Strategy} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StrategyItemProvider strategyItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Strategy}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStrategyAdapter() {
		if (strategyItemProvider == null) {
			strategyItemProvider = new StrategyItemProvider(this);
		}

		return strategyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Matrix} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MatrixItemProvider matrixItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Matrix}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMatrixAdapter() {
		if (matrixItemProvider == null) {
			matrixItemProvider = new MatrixItemProvider(this);
		}

		return matrixItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Include} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IncludeItemProvider includeItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Include}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIncludeAdapter() {
		if (includeItemProvider == null) {
			includeItemProvider = new IncludeItemProvider(this);
		}

		return includeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Exclude} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExcludeItemProvider excludeItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Exclude}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExcludeAdapter() {
		if (excludeItemProvider == null) {
			excludeItemProvider = new ExcludeItemProvider(this);
		}

		return excludeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Workflow_call} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Workflow_callItemProvider workflow_callItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Workflow_call}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkflow_callAdapter() {
		if (workflow_callItemProvider == null) {
			workflow_callItemProvider = new Workflow_callItemProvider(this);
		}

		return workflow_callItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Secret} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SecretItemProvider secretItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Secret}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSecretAdapter() {
		if (secretItemProvider == null) {
			secretItemProvider = new SecretItemProvider(this);
		}

		return secretItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Container} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerItemProvider containerItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Container}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerAdapter() {
		if (containerItemProvider == null) {
			containerItemProvider = new ContainerItemProvider(this);
		}

		return containerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Defaults} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DefaultsItemProvider defaultsItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Defaults}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDefaultsAdapter() {
		if (defaultsItemProvider == null) {
			defaultsItemProvider = new DefaultsItemProvider(this);
		}

		return defaultsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Run} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RunItemProvider runItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Run}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRunAdapter() {
		if (runItemProvider == null) {
			runItemProvider = new RunItemProvider(this);
		}

		return runItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Release} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ReleaseItemProvider releaseItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Release}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createReleaseAdapter() {
		if (releaseItemProvider == null) {
			releaseItemProvider = new ReleaseItemProvider(this);
		}

		return releaseItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pt.isep.yamldslgen.github_actions.Input} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InputItemProvider inputItemProvider;

	/**
	 * This creates an adapter for a {@link pt.isep.yamldslgen.github_actions.Input}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInputAdapter() {
		if (inputItemProvider == null) {
			inputItemProvider = new InputItemProvider(this);
		}

		return inputItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (keyValuePairItemProvider != null)
			keyValuePairItemProvider.dispose();
		if (githubActionsItemProvider != null)
			githubActionsItemProvider.dispose();
		if (jobItemProvider != null)
			jobItemProvider.dispose();
		if (stepItemProvider != null)
			stepItemProvider.dispose();
		if (onItemProvider != null)
			onItemProvider.dispose();
		if (pushItemProvider != null)
			pushItemProvider.dispose();
		if (pull_requestItemProvider != null)
			pull_requestItemProvider.dispose();
		if (permissionsItemProvider != null)
			permissionsItemProvider.dispose();
		if (scheduleItemProvider != null)
			scheduleItemProvider.dispose();
		if (workflow_dispatchItemProvider != null)
			workflow_dispatchItemProvider.dispose();
		if (environmentItemProvider != null)
			environmentItemProvider.dispose();
		if (concurrencyItemProvider != null)
			concurrencyItemProvider.dispose();
		if (strategyItemProvider != null)
			strategyItemProvider.dispose();
		if (matrixItemProvider != null)
			matrixItemProvider.dispose();
		if (includeItemProvider != null)
			includeItemProvider.dispose();
		if (excludeItemProvider != null)
			excludeItemProvider.dispose();
		if (workflow_callItemProvider != null)
			workflow_callItemProvider.dispose();
		if (secretItemProvider != null)
			secretItemProvider.dispose();
		if (containerItemProvider != null)
			containerItemProvider.dispose();
		if (defaultsItemProvider != null)
			defaultsItemProvider.dispose();
		if (runItemProvider != null)
			runItemProvider.dispose();
		if (releaseItemProvider != null)
			releaseItemProvider.dispose();
		if (inputItemProvider != null)
			inputItemProvider.dispose();
	}

}
