/*
 * generated by Xtext 2.42.0
 */
package pt.isep.yamldslgen.dockercompose.xtext;

import org.eclipse.xtext.parser.antlr.Lexer;
import org.eclipse.xtext.parser.antlr.LexerBindings;


import com.google.inject.Binder;
import com.google.inject.name.Names;

import pt.isep.yamldslgen.dockercompose.xtext.parser.antlr.MyDslIndentationAwareLexer;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DcDslRuntimeModule extends AbstractDcDslRuntimeModule {
	/**
	 * Swap the generated {@code InternalMyDslLexer} for our indentation-aware
	 * subclass. This override replaces the binding produced by the parent
	 * {@code AbstractMyDslRuntimeModule#configureRuntimeLexer} so every time
	 * Xtext asks the injector for a runtime {@link Lexer}, it receives our
	 * {@link MyDslIndentationAwareLexer} instead.
	 */
	@Override
	public void configureRuntimeLexer(Binder binder) {
		binder.bind(Lexer.class)
				.annotatedWith(Names.named(LexerBindings.RUNTIME))
				.to(MyDslIndentationAwareLexer.class);
	}
}
